sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install: pip install tox-travis
script: tox
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
