sudo: false
language: python
python:
  - "3.6"
install: pip install tox-travis
dist: trusty
addons:
  chrome: stable
#before_script:
#  - wget http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
#  - unzip chromedriver_linux64.zip -d
#  /home/travis/virtualenv/python3.6.3/bin/
#  - export CHROME_BIN=chromium-browser
script: tox
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
