vowels = [ "অ", "আ", "ই", "ঈ", "উ", "ঊ", "ঋ", "ৠ", "ঌ", "ৡ", "ऎ", "এ", "ঐ", "ऒ", "ও", "ঔ",]
vowel_marks = [ "া", "ি", "ী", "ু", "ূ", "ৃ", "ৄ", "ৢ", "ৣ", "ॆ", "ে", "ৈ", "ॊ", "ো", "ৌ",]
yogavaahas = [ "ং", "ঃ", "ঁ",]
virama = [ "্",]
consonants = [ "ক", "খ", "গ", "ঘ", "ঙ", "চ", "ছ", "জ", "ঝ", "ঞ", "ট", "ঠ", "ড", "ঢ", "ণ", "ত", "থ", "দ", "ধ", "ন", "প", "ফ", "ব", "ভ", "ম", "য", "র", "ল", "ব", "শ", "ষ", "স", "হ", "ল়", "ক্ষ", "জ্ঞ",]
symbols = [ "০", "১", "২", "৩", "৪", "৫", "৬", "৭", "৮", "৯", "ওঁ", "ঽ", "।", "॥",]
zwj = [ "",]
skip = [ "",]
accents = [ "॑", "॒",]
candra = [ "ে",]
extra_consonants = [ "ক়", "খ়", "গ়", "জ়", "ড়", "ঢ়", "ফ়", "য়", "র়", "ষ়",]
