[vowels]
"рдЕ" = "ЁС░А"
"рдЖ" = "ЁС░Б"
"рдЗ" = "ЁС░В"
"рдИ" = "ЁС░Г"
"рдЙ" = "ЁС░Д"
"рдК" = "ЁС░Е"
"рдЛ" = "ЁС░Ж"
"реа" = "ЁС░З"
"рдМ" = "ЁС░И"
"реб" = "ЁС░И"
"рдО" = "ЁС░К"
"рдП" = "ЁС░К"
"рдР" = "ЁС░Л"
"рдТ" = "ЁС░М"
"рдУ" = "ЁС░М"
"рдФ" = "ЁС░Н"

[vowel_marks]
"рд╛" = "ЁС░п"
"рд┐" = "ЁС░░"
"реА" = "ЁС░▒"
"реБ" = "ЁС░▓"
"реВ" = "ЁС░│"
"реГ" = "ЁС░┤"
"реД" = "ЁС░╡"
"рев" = "ЁС░╢"
"рег" = "ЁС░╢"
"реЖ" = "ЁС░╕"
"реЗ" = "ЁС░╕"
"реИ" = "ЁС░╣"
"реК" = "ЁС░║"
"реЛ" = "ЁС░║"
"реМ" = "ЁС░╗"

[yogavaahas]
"рдВ" = "ЁС░╜"
"рдГ" = "ЁС░╛"
"рдБ" = "ЁС░╝"

[virama]
"реН" = "ЁС░┐"

[consonants]
"рдХ" = "ЁС░О"
"рдЦ" = "ЁС░П"
"рдЧ" = "ЁС░Р"
"рдШ" = "ЁС░С"
"рдЩ" = "ЁС░Т"
"рдЪ" = "ЁС░У"
"рдЫ" = "ЁС░Ф"
"рдЬ" = "ЁС░Х"
"рдЭ" = "ЁС░Ц"
"рдЮ" = "ЁС░Ч"
"рдЯ" = "ЁС░Ш"
"рда" = "ЁС░Щ"
"рдб" = "ЁС░Ъ"
"рдв" = "ЁС░Ы"
"рдг" = "ЁС░Ь"
"рдд" = "ЁС░Э"
"рде" = "ЁС░Ю"
"рдж" = "ЁС░Я"
"рдз" = "ЁС░а"
"рди" = "ЁС░б"
"рдк" = "ЁС░в"
"рдл" = "ЁС░г"
"рдм" = "ЁС░д"
"рдн" = "ЁС░е"
"рдо" = "ЁС░ж"
"рдп" = "ЁС░з"
"рд░" = "ЁС░и"
"рд▓" = "ЁС░й"
"рд╡" = "ЁС░к"
"рд╢" = "ЁС░л"
"рд╖" = "ЁС░м"
"рд╕" = "ЁС░н"
"рд╣" = "ЁС░о"
"рд│" = "ЁС░й"
"рдХреНрд╖" = "ЁС░ОЁС░┐ЁС░м"
"рдЬреНрдЮ" = "ЁС░ХЁС░┐ЁС░Ч"

[symbols]
"реж" = "ЁС▒Р"
"рез" = "ЁС▒С"
"реи" = "ЁС▒Т"
"рей" = "ЁС▒У"
"рек" = "ЁС▒Ф"
"рел" = "ЁС▒Х"
"рем" = "ЁС▒Ц"
"рен" = "ЁС▒Ч"
"рео" = "ЁС▒Ш"
"реп" = "ЁС▒Щ"
"реР" = "ЁС░МЁС░╝"
"рд╜" = "ЁС▒А"
"ред" = "ЁС▒Б"
"рее" = "ЁС▒В"

[zwj]
"\u200d" = "\u200d"

[skip]
"" = ""

[accents]
"реС" = "реС"
"реТ" = "реТ"

[candra]
"реЕ" = "ЁС░╕"

[extra_consonants]
"реШ" = "ЁС░О"
"реЩ" = "ЁС░П"
"реЪ" = "ЁС░Р"
"реЫ" = "ЁС░Х"
"реЬ" = "ЁС░Ъ"
"рдврд╝" = "ЁС░Ы"
"реЮ" = "ЁС░г"
"реЯ" = "ЁС░з"
"рд▒" = "ЁС░и"
