vowels = [ "အ", "အာ", "ဣ", "ဤ", "ဥ", "ဦ", "ၒ", "ၓ", "ၔ", "ၕ", "ဧ", "ဧ", "အဲ", "ဩ", "ဩ", "ဪ",]
vowel_marks = [ "ာ", "ိ", "ီ", "ု", "ူ", "ၖ", "ၗ", "ၘ", "ၙ", "ေ", "ေ", "ဲ", "ော", "ော", "ော်",]
yogavaahas = [ "ံ", "း", "ံ",]
virama = [ "်",]
consonants = [ "က", "ခ", "ဂ", "ဃ", "င", "စ", "ဆ", "ဇ", "ဈ", "ဉ", "ဋ", "ဌ", "ဍ", "ဎ", "ဏ", "တ", "ထ", "ဒ", "ဓ", "န", "ပ", "ဖ", "ဗ", "ဘ", "မ", "ယ", "ရ", "လ", "ဝ", "ၐ", "ၑ", "သ", "ဟ", "ဠ", "က္ၑ", "ဇ္ဉ",]
symbols = [ "၀", "၁", "၂", "၃", "၄", "၅", "၆", "၇", "၈", "၉", "ဩံ", "'", "၊", "။",]
zwj = [ "\u200d",]
skip = [ "",]
accents = [ "॑", "॒",]
candra = [ "ေ",]
extra_consonants = [ "က", "ခ", "ဂ", "ဇ", "ဍ", "ဎ", "ဖ", "ယ", "ရ",]
