vowels = [ "अ", "आ", "इ", "ई", "उ", "ऊ", "ऋ", "ॠ", "ऌ", "ॡ", "ऎ", "ए", "ऐ", "ऒ", "ओ", "औ", "ऍ", "ऑ",]
vowel_marks = [ "ा", "ि", "ी", "ु", "ू", "ृ", "ॄ", "ॢ", "ॣ", "ॆ", "े", "ै", "ॊ", "ो", "ौ", "ॅ", "ॉ",]
yogavaahas = [ "ं", "ः", "ँ", "ᳵ", "ᳶ", "ꣳ",]
virama = [ "्",]
consonants = [ "क", "ख", "ग", "घ", "ङ", "च", "छ", "ज", "झ", "ञ", "ट", "ठ", "ड", "ढ", "ण", "त", "थ", "द", "ध", "न", "प", "फ", "ब", "भ", "म", "य", "र", "ल", "व", "श", "ष", "स", "ह", "ळ", "क्ष", "ज्ञ",]
symbols = [ "०", "१", "२", "३", "४", "५", "६", "७", "८", "९", "ॐ", "ऽ", "।", "॥",]
zwj = [ "\u200d",]
zwnj = [ "\u200c",]
skip = [ "",]
accents = [ "॑", "॒", "᳡", "꣡", "꣢", "꣣", "꣤", "꣥", "꣦", "꣧", "꣨", "꣩", "꣪", "꣫", "꣬", "꣭", "꣮", "꣯", "꣰", "꣱",]
candra = [ "ॅ",]
extra_consonants = [ "क़", "ख़", "ग़", "ज़", "ड़", "ढ़", "फ़", "य़", "ऱ", "ऴ", "ऩ",]

[alternates]
"क़" = [ "क़",]
"ख़" = [ "ख़",]
"फ़" = [ "फ़",]
"ड़" = [ "ड़",]
"ग़" = [ "ग़",]
"ढ़" = [ "ढ़",]
"ज़" = [ "य़",]
