[vowels]
"अ" = "अ"
"आ" = "आ"
"इ" = "इ"
"ई" = "ई"
"उ" = "उ"
"ऊ" = "ऊ"
"ऋ" = "ऋ"
"ॠ" = "ॠ"
"ऌ" = "ऌ"
"ॡ" = "ॡ"
"ऎ" = "ऎ"
"ए" = "ए"
"ऐ" = "ऐ"
"ऒ" = "ऒ"
"ओ" = "ओ"
"औ" = "औ"
"ऍ" = "ऍ"
"ऑ" = "ऑ"

[vowel_marks]
"ा" = "ा"
"ि" = "ि"
"ी" = "ी"
"ु" = "ु"
"ू" = "ू"
"ृ" = "ृ"
"ॄ" = "ॄ"
"ॢ" = "ॢ"
"ॣ" = "ॣ"
"ॆ" = "ॆ"
"े" = "े"
"ै" = "ै"
"ॊ" = "ॊ"
"ो" = "ो"
"ौ" = "ौ"
"ॅ" = "ॅ"
"ॉ" = "ॉ"

[yogavaahas]
"ं" = "ं"
"ः" = "ः"
"ँ" = "ँ"
"ᳵ" = "ᳵ"
"ᳶ" = "ᳶ"
"ꣳ" = "ꣳ"

[virama]
"्" = "्"

[consonants]
"क" = "क"
"ख" = "ख"
"ग" = "ग"
"घ" = "घ"
"ङ" = "ङ"
"च" = "च"
"छ" = "छ"
"ज" = "ज"
"झ" = "झ"
"ञ" = "ञ"
"ट" = "ट"
"ठ" = "ठ"
"ड" = "ड"
"ढ" = "ढ"
"ण" = "ण"
"त" = "त"
"थ" = "थ"
"द" = "द"
"ध" = "ध"
"न" = "न"
"प" = "प"
"फ" = "फ"
"ब" = "ब"
"भ" = "भ"
"म" = "म"
"य" = "य"
"र" = "र"
"ल" = "ल"
"व" = "व"
"श" = "श"
"ष" = "ष"
"स" = "स"
"ह" = "ह"
"ळ" = "ळ"
"क्ष" = "क्ष"
"ज्ञ" = "ज्ञ"

[symbols]
"०" = "०"
"१" = "१"
"२" = "२"
"३" = "३"
"४" = "४"
"५" = "५"
"६" = "६"
"७" = "७"
"८" = "८"
"९" = "९"
"ॐ" = "ॐ"
"ऽ" = "ऽ"
"।" = "।"
"॥" = "॥"

[zwj]
"\u200d" = "\u200d"

[zwnj]
"\u200c" = "\u200c"

[skip]
"" = ""

[accents]
"॑" = "॑"
"॒" = "॒"
"᳡" = "᳡"
"꣡" = "꣡"
"꣢" = "꣢"
"꣣" = "꣣"
"꣤" = "꣤"
"꣥" = "꣥"
"꣦" = "꣦"
"꣧" = "꣧"
"꣨" = "꣨"
"꣩" = "꣩"
"꣪" = "꣪"
"꣫" = "꣫"
"꣬" = "꣬"
"꣭" = "꣭"
"꣮" = "꣮"
"꣯" = "꣯"
"꣰" = "꣰"
"꣱" = "꣱"

[candra]
"ॅ" = "ॅ"

[extra_consonants]
"क़" = "क़"
"ख़" = "ख़"
"ग़" = "ग़"
"ज़" = "ज़"
"ड़" = "ड़"
"ढ़" = "ढ़"
"फ़" = "फ़"
"य़" = "य़"
"ऱ" = "ऱ"
"ऴ" = "ऴ"
"ऩ" = "ऩ"

[alternates]
"क़" = [ "क़",]
"ख़" = [ "ख़",]
"फ़" = [ "फ़",]
"ड़" = [ "ड़",]
"ग़" = [ "ग़",]
"ढ़" = [ "ढ़",]
"ज़" = [ "य़",]
