vowels = [ "അ", "ആ", "ഇ", "ഈ", "ഉ", "ഊ", "ഋ", "ൠ", "ഌ", "ൡ", "ഏ", "ഏ", "ഐ", "ഓ", "ഓ", "ഔ",]
vowel_marks = [ "ാ", "ി", "ീ", "ു", "ൂ", "ൃ", "ൄ", "ൢ", "ൣ", "േ", "േ", "ൈ", "ോ", "ോ", "ൗ",]
yogavaahas = [ "ം", "ഃ", "ം",]
virama = [ "്",]
consonants = [ "ക", "ഖ", "ഗ", "ഘ", "ങ", "ച", "ഛ", "ജ", "ഝ", "ഞ", "ട", "ഠ", "ഡ", "ഢ", "ണ", "ത", "ഥ", "ദ", "ധ", "ന", "പ", "ഫ", "ബ", "ഭ", "മ", "യ", "ര", "ല", "വ", "ശ", "ഷ", "സ", "ഹ", "ള", "ക്ഷ", "ജ്ഞ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ഓം", "ഽ", "।", "॥",]
zwj = [ "\u200d",]
skip = [ "",]
accents = [ "॑", "॒",]
candra = [ "േ",]
extra_consonants = [ "ക", "ഖ", "ഗ", "ജ", "ഡ", "ഢ", "ഫ", "യ", "ര",]
