[vowels]
"अ" = "ਅ"
"आ" = "ਆ"
"इ" = "ਇ"
"ई" = "ਈ"
"उ" = "ਉ"
"ऊ" = "ਊ"
"ऋ" = ""
"ॠ" = ""
"ऌ" = ""
"ॡ" = ""
"ऎ" = ""
"ए" = "ਏ"
"ऐ" = "ਐ"
"ऒ" = ""
"ओ" = "ਓ"
"औ" = "ਔ"

[vowel_marks]
"ा" = "ਾ"
"ि" = "ਿ"
"ी" = "ੀ"
"ु" = "ੁ"
"ू" = "ੂ"
"ृ" = ""
"ॄ" = ""
"ॢ" = ""
"ॣ" = ""
"ॆ" = ""
"े" = "ੇ"
"ै" = "ੈ"
"ॊ" = ""
"ो" = "ੋ"
"ौ" = "ੌ"

[yogavaahas]
"ं" = "ਂ"
"ः" = "ਃ"
"ँ" = "ਁ"

[virama]
"्" = "੍"

[consonants]
"क" = "ਕ"
"ख" = "ਖ"
"ग" = "ਗ"
"घ" = "ਘ"
"ङ" = "ਙ"
"च" = "ਚ"
"छ" = "ਛ"
"ज" = "ਜ"
"झ" = "ਝ"
"ञ" = "ਞ"
"ट" = "ਟ"
"ठ" = "ਠ"
"ड" = "ਡ"
"ढ" = "ਢ"
"ण" = "ਣ"
"त" = "ਤ"
"थ" = "ਥ"
"द" = "ਦ"
"ध" = "ਧ"
"न" = "ਨ"
"प" = "ਪ"
"फ" = "ਫ"
"ब" = "ਬ"
"भ" = "ਭ"
"म" = "ਮ"
"य" = "ਯ"
"र" = "ਰ"
"ल" = "ਲ"
"व" = "ਵ"
"श" = "ਸ਼"
"ष" = ""
"स" = "ਸ"
"ह" = "ਹ"
"ळ" = "ਲ਼"
"क्ष" = "ਕ੍ਸ਼"
"ज्ञ" = "ਜ੍ਞ"

[symbols]
"०" = "੦"
"१" = "੧"
"२" = "੨"
"३" = "੩"
"४" = "੪"
"५" = "੫"
"६" = "੬"
"७" = "੭"
"८" = "੮"
"९" = "੯"
"ॐ" = "ੴ"
"ऽ" = "ऽ"
"।" = "।"
"॥" = "॥"

[alternates]
"ਂ" = [ "ੰ",]

[extra_consonants]
"क़" = "ਕ਼"
"ख़" = "ਖ਼"
"ग़" = "ਗ਼"
"ज़" = "ਜ਼"
"ड़" = "ੜ"
"ढ़" = "ਢ਼"
"फ़" = "ਫ਼"
"य़" = "ਯ਼"
"ऱ" = "ਰ਼"
"ऴ" = "ਲ਼਼"
"ऩ" = "ਨ਼"
