vowels = [ "ਅ", "ਆ", "ਇ", "ਈ", "ਉ", "ਊ", "", "", "", "", "", "ਏ", "ਐ", "", "ਓ", "ਔ",]
vowel_marks = [ "ਾ", "ਿ", "ੀ", "ੁ", "ੂ", "", "", "", "", "", "ੇ", "ੈ", "", "ੋ", "ੌ",]
yogavaahas = [ "ਂ", "ਃ", "ਁ",]
virama = [ "੍",]
consonants = [ "ਕ", "ਖ", "ਗ", "ਘ", "ਙ", "ਚ", "ਛ", "ਜ", "ਝ", "ਞ", "ਟ", "ਠ", "ਡ", "ਢ", "ਣ", "ਤ", "ਥ", "ਦ", "ਧ", "ਨ", "ਪ", "ਫ", "ਬ", "ਭ", "ਮ", "ਯ", "ਰ", "ਲ", "ਵ", "ਸ਼", "", "ਸ", "ਹ", "ਲ਼", "ਕ੍ਸ਼", "ਜ੍ਞ",]
symbols = [ "੦", "੧", "੨", "੩", "੪", "੫", "੬", "੭", "੮", "੯", "ੴ", "ऽ", "।", "॥",]
extra_consonants = [ "ਕ਼", "ਖ਼", "ਗ਼", "ਜ਼", "ੜ", "ਢ਼", "ਫ਼", "ਯ਼", "ਰ਼", "ਲ਼਼", "ਨ਼",]

[alternates]
"ਂ" = [ "ੰ",]
