[vowels]
"अ" = "ꦄ"
"आ" = "ꦄꦴ"
"इ" = "ꦆ"
"ई" = "ꦇ"
"उ" = "ꦈ"
"ऊ" = "ꦈꦴ"
"ऋ" = "ꦉ"
"ॠ" = "ꦉꦴ"
"ऌ" = "ꦊ"
"ॡ" = "ꦋ"
"ऎ" = ""
"ए" = "ꦌ"
"ऐ" = "ꦍ"
"ऒ" = ""
"ओ" = "ꦎ"
"औ" = "ꦎꦴ"

[vowel_marks]
"ा" = "ꦴ"
"ि" = "ꦶ"
"ी" = "ꦷ"
"ु" = "ꦸ"
"ू" = "ꦹ"
"ृ" = "ꦽ"
"ॄ" = "꧀ꦉꦴ"
"ॢ" = "꧀ꦊ"
"ॣ" = "꧀ꦋ"
"ॆ" = ""
"े" = "ꦺ"
"ै" = "ꦻ"
"ॊ" = ""
"ो" = "ꦺꦴ"
"ौ" = "ꦻꦴ"

[yogavaahas]
"ं" = "ꦁ"
"ः" = "ꦃ"
"ँ" = "ꦀ"

[virama]
"्" = "꧀"

[consonants]
"क" = "ꦏ"
"ख" = "ꦑ"
"ग" = "ꦒ"
"घ" = "ꦓ"
"ङ" = "ꦔ"
"च" = "ꦕ"
"छ" = "ꦖ"
"ज" = "ꦗ"
"झ" = "ꦙ"
"ञ" = "ꦚ"
"ट" = "ꦛ"
"ठ" = "ꦜ"
"ड" = "ꦝ"
"ढ" = "ꦞ"
"ण" = "ꦟ"
"त" = "ꦠ"
"थ" = "ꦡ"
"द" = "ꦢ"
"ध" = "ꦣ"
"न" = "ꦤ"
"प" = "ꦥ"
"फ" = "ꦦ"
"ब" = "ꦧ"
"भ" = "ꦨ"
"म" = "ꦩ"
"य" = "ꦪ"
"र" = "ꦫ"
"ल" = "ꦭ"
"व" = "ꦮ"
"श" = "ꦯ"
"ष" = "ꦰ"
"स" = "ꦱ"
"ह" = "ꦲ"
"ळ" = "ꦭ꦳"
"क्ष" = "ꦏ꧀ꦰ"
"ज्ञ" = "ꦗ꧀ꦚ"

[symbols]
"०" = "꧐"
"१" = "꧑"
"२" = "꧒"
"३" = "꧓"
"४" = "꧔"
"५" = "꧕"
"६" = "꧖"
"७" = "꧗"
"८" = "꧘"
"९" = "꧙"
"ॐ" = "ꦎꦀ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ꦼ"
