vowels = [ "ꦄ", "ꦄꦴ", "ꦆ", "ꦇ", "ꦈ", "ꦈꦴ", "ꦉ", "ꦉꦴ", "ꦊ", "ꦋ", "", "ꦌ", "ꦍ", "", "ꦎ", "ꦎꦴ",]
vowel_marks = [ "ꦴ", "ꦶ", "ꦷ", "ꦸ", "ꦹ", "ꦽ", "꧀ꦉꦴ", "꧀ꦊ", "꧀ꦋ", "", "ꦺ", "ꦻ", "", "ꦺꦴ", "ꦻꦴ",]
yogavaahas = [ "ꦁ", "ꦃ", "ꦀ",]
virama = [ "꧀",]
consonants = [ "ꦏ", "ꦑ", "ꦒ", "ꦓ", "ꦔ", "ꦕ", "ꦖ", "ꦗ", "ꦙ", "ꦚ", "ꦛ", "ꦜ", "ꦝ", "ꦞ", "ꦟ", "ꦠ", "ꦡ", "ꦢ", "ꦣ", "ꦤ", "ꦥ", "ꦦ", "ꦧ", "ꦨ", "ꦩ", "ꦪ", "ꦫ", "ꦭ", "ꦮ", "ꦯ", "ꦰ", "ꦱ", "ꦲ", "ꦭ꦳", "ꦏ꧀ꦰ", "ꦗ꧀ꦚ",]
symbols = [ "꧐", "꧑", "꧒", "꧓", "꧔", "꧕", "꧖", "꧗", "꧘", "꧙", "ꦎꦀ", "'", "।", "॥",]
candra = [ "ꦼ",]
