[vowels]
"अ" = "ಅ"
"आ" = "ಆ"
"इ" = "ಇ"
"ई" = "ಈ"
"उ" = "ಉ"
"ऊ" = "ಊ"
"ऋ" = "ಋ"
"ॠ" = "ೠ"
"ऌ" = "ಌ"
"ॡ" = "ೡ"
"ऎ" = "ಎ"
"ए" = "ಏ"
"ऐ" = "ಐ"
"ऒ" = "ಒ"
"ओ" = "ಓ"
"औ" = "ಔ"

[vowel_marks]
"ा" = "ಾ"
"ि" = "ಿ"
"ी" = "ೀ"
"ु" = "ು"
"ू" = "ೂ"
"ृ" = "ೃ"
"ॄ" = "ೄ"
"ॢ" = "ೢ"
"ॣ" = "ೣ"
"ॆ" = "ೆ"
"े" = "ೇ"
"ै" = "ೈ"
"ॊ" = "ೊ"
"ो" = "ೋ"
"ौ" = "ೌ"

[yogavaahas]
"ं" = "ಂ"
"ः" = "ಃ"
"ँ" = "ಁ"
"ᳵ" = "ೱ"
"ᳶ" = "ೲ"

[virama]
"्" = "್"

[consonants]
"क" = "ಕ"
"ख" = "ಖ"
"ग" = "ಗ"
"घ" = "ಘ"
"ङ" = "ಙ"
"च" = "ಚ"
"छ" = "ಛ"
"ज" = "ಜ"
"झ" = "ಝ"
"ञ" = "ಞ"
"ट" = "ಟ"
"ठ" = "ಠ"
"ड" = "ಡ"
"ढ" = "ಢ"
"ण" = "ಣ"
"त" = "ತ"
"थ" = "ಥ"
"द" = "ದ"
"ध" = "ಧ"
"न" = "ನ"
"प" = "ಪ"
"फ" = "ಫ"
"ब" = "ಬ"
"भ" = "ಭ"
"म" = "ಮ"
"य" = "ಯ"
"र" = "ರ"
"ल" = "ಲ"
"व" = "ವ"
"श" = "ಶ"
"ष" = "ಷ"
"स" = "ಸ"
"ह" = "ಹ"
"ळ" = "ಳ"
"क्ष" = "ಕ್ಷ"
"ज्ञ" = "ಜ್ಞ"

[symbols]
"०" = "೦"
"१" = "೧"
"२" = "೨"
"३" = "೩"
"४" = "೪"
"५" = "೫"
"६" = "೬"
"७" = "೭"
"८" = "೮"
"९" = "೯"
"ॐ" = "ಓಂ"
"ऽ" = "ಽ"
"।" = "।"
"॥" = "॥"

[extra_consonants]
"क़" = "ಕ಼"
"ख़" = "ಖ಼"
"ग़" = "ಗ಼"
"ज़" = "ಜ಼"
"ड़" = "ಡ಼"
"ढ़" = "ಢ಼"
"फ़" = "ಫ಼"
"य़" = "ಯ಼"
"ऱ" = "ಱ"
"ऴ" = "ೞ"
