[vowels]
"अ" = "အ"
"आ" = "အႃ"
"इ" = "အိ"
"ई" = "အီ"
"उ" = "အု"
"ऊ" = "အူ"
"ऋ" = "ရိ"
"ॠ" = "ရီ"
"ऌ" = "လိ"
"ॡ" = "လီ"
"ऎ" = ""
"ए" = "အေ"
"ऐ" = "အႆ"
"ऒ" = ""
"ओ" = "အူဝ်"
"औ" = "အဝ်"

[vowel_marks]
"ा" = "ႃ"
"ि" = "ိ"
"ी" = "ီ"
"ु" = "ု"
"ू" = "ူ"
"ृ" = "်ရိ"
"ॄ" = "်ရီ"
"ॢ" = "်လိ"
"ॣ" = "်လီ"
"ॆ" = ""
"े" = "ေ"
"ै" = "ႆ"
"ॊ" = ""
"ो" = "ူဝ်"
"ौ" = "ဝ်"

[yogavaahas]
"ं" = "ံ"
"ः" = "း"
"ँ" = "ံ"

[virama]
"्" = "်"

[consonants]
"क" = "က"
"ख" = "ၵ"
"ग" = "ꩠ"
"घ" = "ၷ"
"ङ" = "င"
"च" = "ꩡ"
"छ" = "ꩢ"
"ज" = "ꩣ"
"झ" = "ꩤ"
"ञ" = "ꩥ"
"ट" = "ꩦ"
"ठ" = "ꩧ"
"ड" = "ꩨ"
"ढ" = "ꩩ"
"ण" = "ꧣ"
"त" = "တ"
"थ" = "ထ"
"द" = "ၻ"
"ध" = "ꩪ"
"न" = "ꩫ"
"प" = "ပ"
"फ" = "ၸ"
"ब" = "ၿ"
"भ" = "ၹ"
"म" = "မ"
"य" = "ယ"
"र" = "ꩳ"
"ल" = "လ"
"व" = "ဝ"
"श" = "ꩬ"
"ष" = "ꩬ"
"स" = "ꩬ"
"ह" = "ꩭ"
"ळ" = "ꩮ"
"क्ष" = "က်ꩬ"
"ज्ञ" = "ꩣ်ꩥ"

[symbols]
"०" = "႐"
"१" = "႑"
"२" = "႒"
"३" = "႓"
"४" = "႔"
"५" = "႕"
"६" = "႖"
"७" = "႗"
"८" = "႘"
"९" = "႙"
"ॐ" = "အေႃံ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ႄ"
