vowels = [ "အ", "အႃ", "အိ", "အီ", "အု", "အူ", "ရိ", "ရီ", "လိ", "လီ", "", "အေ", "အႆ", "", "အူဝ်", "အဝ်",]
vowel_marks = [ "ႃ", "ိ", "ီ", "ု", "ူ", "်ရိ", "်ရီ", "်လိ", "်လီ", "", "ေ", "ႆ", "", "ူဝ်", "ဝ်",]
yogavaahas = [ "ံ", "း", "ံ",]
virama = [ "်",]
consonants = [ "က", "ၵ", "ꩠ", "ၷ", "င", "ꩡ", "ꩢ", "ꩣ", "ꩤ", "ꩥ", "ꩦ", "ꩧ", "ꩨ", "ꩩ", "ꧣ", "တ", "ထ", "ၻ", "ꩪ", "ꩫ", "ပ", "ၸ", "ၿ", "ၹ", "မ", "ယ", "ꩳ", "လ", "ဝ", "ꩬ", "ꩬ", "ꩬ", "ꩭ", "ꩮ", "က်ꩬ", "ꩣ်ꩥ",]
symbols = [ "႐", "႑", "႒", "႓", "႔", "႕", "႖", "႗", "႘", "႙", "အေႃံ", "'", "।", "॥",]
candra = [ "ႄ",]
