[vowels]
"рдЕ" = "ЁРиА"
"рдЖ" = "ЁРиАЁРиМ"
"рдЗ" = "ЁРиАЁРиБ"
"рдИ" = "ЁРиАЁРиБЁРиМ"
"рдЙ" = "ЁРиАЁРиВ"
"рдК" = "ЁРиАЁРиВЁРиМ"
"рдЛ" = "ЁРиАЁРиГ"
"реа" = "ЁРиАЁРиГЁРиМ"
"рдМ" = "ЁРилЁРиВ"
"реб" = "ЁРилЁРиВЁРиМ"
"рдО" = ""
"рдП" = "ЁРиАЁРиЕ"
"рдР" = "ЁРиАЁРиЕЁРиМ"
"рдТ" = ""
"рдУ" = "ЁРиАЁРиЖ"
"рдФ" = "ЁРиАЁРиЖЁРиМ"

[vowel_marks]
"рд╛" = "ЁРиМ"
"рд┐" = "ЁРиБ"
"реА" = "ЁРиБЁРиМ"
"реБ" = "ЁРиВ"
"реВ" = "ЁРиВЁРиМ"
"реГ" = "ЁРиГ"
"реД" = "ЁРиГЁРиМ"
"рев" = "ЁРи┐ЁРилЁРиВ"
"рег" = "ЁРи┐ЁРилЁРиВЁРиМ"
"реЖ" = ""
"реЗ" = "ЁРиЕ"
"реИ" = "ЁРиЕЁРиМ"
"реК" = ""
"реЛ" = "ЁРиЖ"
"реМ" = "ЁРиЖЁРиМ"

[yogavaahas]
"рдВ" = "ЁРиО"
"рдГ" = "ЁРиП"
"рдБ" = "ЁРиО"

[virama]
"реН" = "ЁРи┐"

[consonants]
"рдХ" = "ЁРиР"
"рдЦ" = "ЁРиС"
"рдЧ" = "ЁРиТ"
"рдШ" = "ЁРиУ"
"рдЩ" = "ЁРиг"
"рдЪ" = "ЁРиХ"
"рдЫ" = "ЁРиЦ"
"рдЬ" = "ЁРиЧ"
"рдЭ" = "ЁРиЧ"
"рдЮ" = "ЁРиЩ"
"рдЯ" = "ЁРиЪ"
"рда" = "ЁРиЫ"
"рдб" = "ЁРиЬ"
"рдв" = "ЁРиЭ"
"рдг" = "ЁРиЮ"
"рдд" = "ЁРиЯ"
"рде" = "ЁРиа"
"рдж" = "ЁРиб"
"рдз" = "ЁРив"
"рди" = "ЁРиг"
"рдк" = "ЁРид"
"рдл" = "ЁРие"
"рдм" = "ЁРиж"
"рдн" = "ЁРиз"
"рдо" = "ЁРии"
"рдп" = "ЁРий"
"рд░" = "ЁРик"
"рд▓" = "ЁРил"
"рд╡" = "ЁРим"
"рд╢" = "ЁРин"
"рд╖" = "ЁРио"
"рд╕" = "ЁРип"
"рд╣" = "ЁРи▒"
"рд│" = "ЁРил"
"рдХреНрд╖" = "ЁРиРЁРи┐ЁРио"
"рдЬреНрдЮ" = "ЁРиЧЁРи┐ЁРиЩ"

[symbols]
"реж" = ""
"рез" = "ЁРйА"
"реи" = "ЁРйБ"
"рей" = "ЁРйВ"
"рек" = "ЁРйГ"
"рел" = "ЁРйГЁРйА"
"рем" = "ЁРйГЁРйБ"
"рен" = "ЁРйГЁРйВ"
"рео" = "ЁРйГЁРйГ"
"реп" = "ЁРйГЁРйГЁРйА"
"реР" = "ЁРиАЁРиЕЁРиО"
"рд╜" = ""
"ред" = "ред"
"рее" = "рее"

[candra]
"реЕ" = "ЁРиЕ"
