[vowels]
"अ" = "អ"
"आ" = "អា"
"इ" = "ឥ"
"ई" = "ឦ"
"उ" = "ឧ"
"ऊ" = "ឩ"
"ऋ" = "ឫ"
"ॠ" = "ឬ"
"ऌ" = "ឭ"
"ॡ" = "ឮ"
"ऎ" = ""
"ए" = "ឯ"
"ऐ" = "ឰ"
"ऒ" = ""
"ओ" = "ឱ"
"औ" = "ឳ"

[vowel_marks]
"ा" = "ា"
"ि" = "ិ"
"ी" = "ី"
"ु" = "ុ"
"ू" = "ូ"
"ृ" = "្ឫ"
"ॄ" = "្ឬ"
"ॢ" = "្ឭ"
"ॣ" = "្ឮ"
"ॆ" = ""
"े" = "េ"
"ै" = "ៃ"
"ॊ" = ""
"ो" = "ោ"
"ौ" = "ៅ"

[yogavaahas]
"ं" = "ំ"
"ः" = "ះ"
"ँ" = "ំ"

[virama]
"्" = "៑"

[consonants]
"क" = "ក"
"ख" = "ខ"
"ग" = "គ"
"घ" = "ឃ"
"ङ" = "ង"
"च" = "ច"
"छ" = "ឆ"
"ज" = "ជ"
"झ" = "ឈ"
"ञ" = "ញ"
"ट" = "ដ"
"ठ" = "ឋ"
"ड" = "ឌ"
"ढ" = "ឍ"
"ण" = "ណ"
"त" = "ត"
"थ" = "ថ"
"द" = "ទ"
"ध" = "ធ"
"न" = "ន"
"प" = "ប"
"फ" = "ផ"
"ब" = "ព"
"भ" = "ភ"
"म" = "ម"
"य" = "យ"
"र" = "រ"
"ल" = "ល"
"व" = "វ"
"श" = "ឝ"
"ष" = "ឞ"
"स" = "ស"
"ह" = "ហ"
"ळ" = "ឡ"
"क्ष" = "ក្ឞ"
"ज्ञ" = "ជ្ញ"

[symbols]
"०" = "០"
"१" = "១"
"२" = "២"
"३" = "៣"
"४" = "៤"
"५" = "៥"
"६" = "៦"
"७" = "៧"
"८" = "៨"
"९" = "៩"
"ॐ" = "ឱំ"
"ऽ" = "ៜ"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "េ"
