vowels = [ "អ", "អា", "ឥ", "ឦ", "ឧ", "ឩ", "ឫ", "ឬ", "ឭ", "ឮ", "", "ឯ", "ឰ", "", "ឱ", "ឳ",]
vowel_marks = [ "ា", "ិ", "ី", "ុ", "ូ", "្ឫ", "្ឬ", "្ឭ", "្ឮ", "", "េ", "ៃ", "", "ោ", "ៅ",]
yogavaahas = [ "ំ", "ះ", "ំ",]
virama = [ "៑",]
consonants = [ "ក", "ខ", "គ", "ឃ", "ង", "ច", "ឆ", "ជ", "ឈ", "ញ", "ដ", "ឋ", "ឌ", "ឍ", "ណ", "ត", "ថ", "ទ", "ធ", "ន", "ប", "ផ", "ព", "ភ", "ម", "យ", "រ", "ល", "វ", "ឝ", "ឞ", "ស", "ហ", "ឡ", "ក្ឞ", "ជ្ញ",]
symbols = [ "០", "១", "២", "៣", "៤", "៥", "៦", "៧", "៨", "៩", "ឱំ", "ៜ", "।", "॥",]
candra = [ "េ",]
