[vowels]
"अ" = "อ"
"आ" = "อา"
"इ" = "อิ"
"ई" = "อี"
"उ" = "อุ"
"ऊ" = "อู"
"ऋ" = "รุ"
"ॠ" = "รู"
"ऌ" = "ลุ"
"ॡ" = "ลู"
"ऎ" = ""
"ए" = "เอ"
"ऐ" = "อยฺ"
"ऒ" = ""
"ओ" = "โอ"
"औ" = "อวฺ"

[vowel_marks]
"ा" = "า"
"ि" = "ิ"
"ी" = "ี"
"ु" = "ุ"
"ू" = "ู"
"ृ" = "ฺฤ"
"ॄ" = "ฺฤๅ"
"ॢ" = "ฺลุ"
"ॣ" = "ฺลู"
"ॆ" = ""
"े" = "เ"
"ै" = "ใ"
"ॊ" = ""
"ो" = "โ"
"ौ" = "วฺ"

[yogavaahas]
"ं" = "ํ"
"ः" = "หฺ"
"ँ" = "ํ"

[virama]
"्" = "ฺ"

[consonants]
"क" = "ก"
"ख" = "ข"
"ग" = "ค"
"घ" = "ฆ"
"ङ" = "ง"
"च" = "จ"
"छ" = "ฉ"
"ज" = "ช"
"झ" = "ฌ"
"ञ" = "ญ"
"ट" = "ฏ"
"ठ" = "ฐ"
"ड" = "ฑ"
"ढ" = "ฒ"
"ण" = "ณ"
"त" = "ต"
"थ" = "ถ"
"द" = "ท"
"ध" = "ธ"
"न" = "น"
"प" = "ป"
"फ" = "ผ"
"ब" = "พ"
"भ" = "ภ"
"म" = "ม"
"य" = "ย"
"र" = "ร"
"ल" = "ล"
"व" = "ว"
"श" = "ส"
"ष" = "ส"
"स" = "ส"
"ह" = "ห"
"ळ" = "ฬ"
"क्ष" = "กฺส"
"ज्ञ" = "ชฺญ"

[symbols]
"०" = "๐"
"१" = "๑"
"२" = "๒"
"३" = "๓"
"४" = "๔"
"५" = "๕"
"६" = "๖"
"७" = "๗"
"८" = "๘"
"९" = "๙"
"ॐ" = "โอํ"
"ऽ" = ""
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "แ"
