vowels = [ "อ", "อา", "อิ", "อี", "อุ", "อู", "รุ", "รู", "ลุ", "ลู", "", "เอ", "อยฺ", "", "โอ", "อวฺ",]
vowel_marks = [ "า", "ิ", "ี", "ุ", "ู", "ฺฤ", "ฺฤๅ", "ฺลุ", "ฺลู", "", "เ", "ใ", "", "โ", "วฺ",]
yogavaahas = [ "ํ", "หฺ", "ํ",]
virama = [ "ฺ",]
consonants = [ "ก", "ข", "ค", "ฆ", "ง", "จ", "ฉ", "ช", "ฌ", "ญ", "ฏ", "ฐ", "ฑ", "ฒ", "ณ", "ต", "ถ", "ท", "ธ", "น", "ป", "ผ", "พ", "ภ", "ม", "ย", "ร", "ล", "ว", "ส", "ส", "ส", "ห", "ฬ", "กฺส", "ชฺญ",]
symbols = [ "๐", "๑", "๒", "๓", "๔", "๕", "๖", "๗", "๘", "๙", "โอํ", "", "।", "॥",]
candra = [ "แ",]
