[vowels]
"अ" = "ອະ"
"आ" = "ອາ"
"इ" = "ອິ"
"ई" = "ອີ"
"उ" = "ອຸ"
"ऊ" = "ອູ"
"ऋ" = "ຣຸ"
"ॠ" = "ຣູ"
"ऌ" = "ລຸ"
"ॡ" = "ລູ"
"ऎ" = ""
"ए" = "ເອ"
"ऐ" = "ໄອ"
"ऒ" = ""
"ओ" = "ໂອ"
"औ" = "ເອົາ"

[vowel_marks]
"ा" = "າ"
"ि" = "ິ"
"ी" = "ີ"
"ु" = "ຸ"
"ू" = "ູ"
"ृ" = "ຣຸ"
"ॄ" = "ຣູ"
"ॢ" = "ລຸ"
"ॣ" = "ລູ"
"ॆ" = ""
"े" = "ເ"
"ै" = "ໄ"
"ॊ" = ""
"ो" = "ໂ"
"ौ" = "ເົາ"

[yogavaahas]
"ं" = "ງ"
"ः" = "ຫ"
"ँ" = "ງ"

[virama]
"्" = ""

[consonants]
"क" = "ກະ"
"ख" = "ຂະ"
"ग" = "ຄະ"
"घ" = "ຄະ"
"ङ" = "ງະ"
"च" = "ຈະ"
"छ" = "ຈະ"
"ज" = "ຊະ"
"झ" = "ຊະ"
"ञ" = "ຍະ"
"ट" = "ຕະ"
"ठ" = "ຖະ"
"ड" = "ທະ"
"ढ" = "ທະ"
"ण" = "ນະ"
"त" = "ຕະ"
"थ" = "ຖະ"
"द" = "ທະ"
"ध" = "ທະ"
"न" = "ນະ"
"प" = "ປະ"
"फ" = "ຜະ"
"ब" = "ພະ"
"भ" = "ພະ"
"म" = "ມະ"
"य" = "ຢະ"
"र" = "ຣະ"
"ल" = "ລະ"
"व" = "ວະ"
"श" = "ສະ"
"ष" = "ສະ"
"स" = "ສະ"
"ह" = "ຫະ"
"ळ" = "ລະ"
"क्ष" = "ກສະ"
"ज्ञ" = "ຊຍະ"

[symbols]
"०" = "໐"
"१" = "໑"
"२" = "໒"
"३" = "໓"
"४" = "໔"
"५" = "໕"
"६" = "໖"
"७" = "໗"
"८" = "໘"
"९" = "໙"
"ॐ" = "ໂອງ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ແະ"
