vowels = [ "ອະ", "ອາ", "ອິ", "ອີ", "ອຸ", "ອູ", "ຣຸ", "ຣູ", "ລຸ", "ລູ", "", "ເອ", "ໄອ", "", "ໂອ", "ເອົາ",]
vowel_marks = [ "າ", "ິ", "ີ", "ຸ", "ູ", "ຣຸ", "ຣູ", "ລຸ", "ລູ", "", "ເ", "ໄ", "", "ໂ", "ເົາ",]
yogavaahas = [ "ງ", "ຫ", "ງ",]
virama = [ "",]
consonants = [ "ກະ", "ຂະ", "ຄະ", "ຄະ", "ງະ", "ຈະ", "ຈະ", "ຊະ", "ຊະ", "ຍະ", "ຕະ", "ຖະ", "ທະ", "ທະ", "ນະ", "ຕະ", "ຖະ", "ທະ", "ທະ", "ນະ", "ປະ", "ຜະ", "ພະ", "ພະ", "ມະ", "ຢະ", "ຣະ", "ລະ", "ວະ", "ສະ", "ສະ", "ສະ", "ຫະ", "ລະ", "ກສະ", "ຊຍະ",]
symbols = [ "໐", "໑", "໒", "໓", "໔", "໕", "໖", "໗", "໘", "໙", "ໂອງ", "'", "।", "॥",]
candra = [ "ແະ",]
