vowels = [ "ອ", "ອາ", "ອິ", "ອີ", "ອຸ", "ອູ", "ຣຸ", "ຣູ", "ລຸ", "ລູ", "", "ເອ", "ໄອ", "", "ໂອ", "ເອົາ",]
vowel_marks = [ "າ", "ິ", "ີ", "ຸ", "ູ", "຺ຣຸ", "຺ຣູ", "຺ລຸ", "຺ລູ", "", "ເ", "ໄ", "", "ໂ", "ເົາ",]
yogavaahas = [ "ໍ", "ຫ໌", "ໍ",]
virama = [ "຺",]
consonants = [ "ກ", "ຂ", "ຄ", "ຆ", "ງ", "ຈ", "ຉ", "ຊ", "ຌ", "ຎ", "ຏ", "ຐ", "ຑ", "ຒ", "ຓ", "ຕ", "ຖ", "ທ", "ຘ", "ນ", "ປ", "ຜ", "ພ", "ຠ", "ມ", "ຍ", "ຣ", "ລ", "ວ", "ຨ", "ຩ", "ສ", "ຫ", "ຬ", "ກ຺ຩ", "ຊ຺ຎ",]
symbols = [ "໐", "໑", "໒", "໓", "໔", "໕", "໖", "໗", "໘", "໙", "ໂອໍ", "'", "।", "॥",]
candra = [ "ແະ",]
