[vowels]
"अ" = "ອ"
"आ" = "ອາ"
"इ" = "ອິ"
"ई" = "ອີ"
"उ" = "ອຸ"
"ऊ" = "ອູ"
"ऋ" = "ຣຸ"
"ॠ" = "ຣູ"
"ऌ" = "ລຸ"
"ॡ" = "ລູ"
"ऎ" = ""
"ए" = "ເອ"
"ऐ" = "ໄອ"
"ऒ" = ""
"ओ" = "ໂອ"
"औ" = "ເອົາ"

[vowel_marks]
"ा" = "າ"
"ि" = "ິ"
"ी" = "ີ"
"ु" = "ຸ"
"ू" = "ູ"
"ृ" = "຺ຣຸ"
"ॄ" = "຺ຣູ"
"ॢ" = "຺ລຸ"
"ॣ" = "຺ລູ"
"ॆ" = ""
"े" = "ເ"
"ै" = "ໄ"
"ॊ" = ""
"ो" = "ໂ"
"ौ" = "ເົາ"

[yogavaahas]
"ं" = "ໍ"
"ः" = "ຫ໌"
"ँ" = "ໍ"

[virama]
"्" = "຺"

[consonants]
"क" = "ກ"
"ख" = "ຂ"
"ग" = "ຄ"
"घ" = "ຆ"
"ङ" = "ງ"
"च" = "ຈ"
"छ" = "ຉ"
"ज" = "ຊ"
"झ" = "ຌ"
"ञ" = "ຎ"
"ट" = "ຏ"
"ठ" = "ຐ"
"ड" = "ຑ"
"ढ" = "ຒ"
"ण" = "ຓ"
"त" = "ຕ"
"थ" = "ຖ"
"द" = "ທ"
"ध" = "ຘ"
"न" = "ນ"
"प" = "ປ"
"फ" = "ຜ"
"ब" = "ພ"
"भ" = "ຠ"
"म" = "ມ"
"य" = "ຍ"
"र" = "ຣ"
"ल" = "ລ"
"व" = "ວ"
"श" = "ຨ"
"ष" = "ຩ"
"स" = "ສ"
"ह" = "ຫ"
"ळ" = "ຬ"
"क्ष" = "ກ຺ຩ"
"ज्ञ" = "ຊ຺ຎ"

[symbols]
"०" = "໐"
"१" = "໑"
"२" = "໒"
"३" = "໓"
"४" = "໔"
"५" = "໕"
"६" = "໖"
"७" = "໗"
"८" = "໘"
"९" = "໙"
"ॐ" = "ໂອໍ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ແະ"
