[vowels]
"अ" = "ᰣ"
"आ" = "ᰣᰦ"
"इ" = "ᰣᰧ"
"ई" = "ᰣᰧᰶ"
"उ" = "ᰣᰪ"
"ऊ" = "ᰣᰫ"
"ऋ" = "ᰛᰪ"
"ॠ" = "ᰛᰫ"
"ऌ" = "ᰜᰪ"
"ॡ" = "ᰜᰫ"
"ऎ" = ""
"ए" = "ᰣᰬ"
"ऐ" = "ᰣᰬ"
"ऒ" = ""
"ओ" = "ᰣᰨ"
"औ" = "ᰣᰩ"

[vowel_marks]
"ा" = "ᰦ"
"ि" = "ᰧ"
"ी" = "ᰧᰶ"
"ु" = "ᰪ"
"ू" = "ᰫ"
"ृ" = "ᰥᰪ"
"ॄ" = "ᰥᰫ"
"ॢ" = "ᰜᰪ"
"ॣ" = "ᰜᰫ"
"ॆ" = ""
"े" = "ᰬ"
"ै" = "ᰬ"
"ॊ" = ""
"ो" = "ᰨ"
"ौ" = "ᰩ"

[yogavaahas]
"ं" = "ᰴ"
"ः" = "ᰝ"
"ँ" = "ᰴ"

[virama]
"्" = ""

[consonants]
"क" = "ᰀ"
"ख" = "ᰂ"
"ग" = "ᰃ"
"घ" = "ᰃ"
"ङ" = "ᰅ"
"च" = "ᰆ"
"छ" = "ᰇ"
"ज" = "ᰈ"
"झ" = "ᰈ"
"ञ" = "ᰉ"
"ट" = "ᱍ"
"ठ" = "ᱎ"
"ड" = "ᱏ"
"ढ" = "ᱏ"
"ण" = "ᰍ"
"त" = "ᰊ"
"थ" = "ᰋ"
"द" = "ᰌ"
"ध" = "ᰌ"
"न" = "ᰍ"
"प" = "ᰎ"
"फ" = "ᰐ"
"ब" = "ᰓ"
"भ" = "ᰓ"
"म" = "ᰕ"
"य" = "ᰚ"
"र" = "ᰛ"
"ल" = "ᰜ"
"व" = "ᰟ"
"श" = "ᰡ"
"ष" = "ᰡ᰷"
"स" = "ᰠ"
"ह" = "ᰝ"
"ळ" = "ᰜ᰷"
"क्ष" = "ᰀᰡ᰷"
"ज्ञ" = "ᰈᰉ"

[symbols]
"०" = "᱀"
"१" = "᱁"
"२" = "᱂"
"३" = "᱃"
"४" = "᱄"
"५" = "᱅"
"६" = "᱆"
"७" = "᱇"
"८" = "᱈"
"९" = "᱉"
"ॐ" = "ᰣᰨᰵ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ᰬ"
