vowels = [ "ᰣ", "ᰣᰦ", "ᰣᰧ", "ᰣᰧᰶ", "ᰣᰪ", "ᰣᰫ", "ᰛᰪ", "ᰛᰫ", "ᰜᰪ", "ᰜᰫ", "", "ᰣᰬ", "ᰣᰬ", "", "ᰣᰨ", "ᰣᰩ",]
vowel_marks = [ "ᰦ", "ᰧ", "ᰧᰶ", "ᰪ", "ᰫ", "ᰥᰪ", "ᰥᰫ", "ᰜᰪ", "ᰜᰫ", "", "ᰬ", "ᰬ", "", "ᰨ", "ᰩ",]
yogavaahas = [ "ᰴ", "ᰝ", "ᰴ",]
virama = [ "",]
consonants = [ "ᰀ", "ᰂ", "ᰃ", "ᰃ", "ᰅ", "ᰆ", "ᰇ", "ᰈ", "ᰈ", "ᰉ", "ᱍ", "ᱎ", "ᱏ", "ᱏ", "ᰍ", "ᰊ", "ᰋ", "ᰌ", "ᰌ", "ᰍ", "ᰎ", "ᰐ", "ᰓ", "ᰓ", "ᰕ", "ᰚ", "ᰛ", "ᰜ", "ᰟ", "ᰡ", "ᰡ᰷", "ᰠ", "ᰝ", "ᰜ᰷", "ᰀᰡ᰷", "ᰈᰉ",]
symbols = [ "᱀", "᱁", "᱂", "᱃", "᱄", "᱅", "᱆", "᱇", "᱈", "᱉", "ᰣᰨᰵ", "'", "।", "॥",]
candra = [ "ᰬ",]
