vowels = [ "ᤀ", "ᤀᤠ", "ᤀᤡ", "ᤀᤡ᤺", "ᤀᤢ", "ᤀ᤺ᤢ", "ᤖᤢ", "ᤖ᤺ᤢ", "ᤗᤢ", "ᤗ᤺ᤢ", "", "ᤀᤣ", "ᤀᤤ", "", "ᤀᤥ", "ᤀᤦ",]
vowel_marks = [ "ᤠ", "ᤡ", "ᤡ᤺", "ᤢ", "᤺ᤢ", "ᤪᤢ", "ᤪ᤺ᤢ", "᤻ᤗᤢ", "᤻ᤗ᤺ᤢ", "", "ᤣ", "ᤤ", "", "ᤥ", "ᤦ",]
yogavaahas = [ "ᤱ", "ᤜ᤻", "ᤱ",]
virama = [ "᤻",]
consonants = [ "ᤁ", "ᤂ", "ᤃ", "ᤄ", "ᤅ", "ᤆ", "ᤇ", "ᤈ", "ᤈ", "ᤏ", "ᤋ", "ᤌ", "ᤍ", "ᤎ", "ᤏ", "ᤋ", "ᤌ", "ᤍ", "ᤎ", "ᤏ", "ᤐ", "ᤑ", "ᤒ", "ᤓ", "ᤔ", "ᤕ", "ᤖ", "ᤗ", "ᤘ", "ᤙ", "ᤙ", "ᤛ", "ᤜ", "ᤗ", "ᤁ᤻ᤙ", "ᤈ᤻ᤏ",]
symbols = [ "᥆", "᥇", "᥈", "᥉", "᥊", "᥋", "᥌", "᥍", "᥎", "᥏", "ᤀᤥᤱ", "'", "।", "॥",]
candra = [ "ᤧ",]
