[vowels]
"अ" = "ᤀ"
"आ" = "ᤀᤠ"
"इ" = "ᤀᤡ"
"ई" = "ᤀᤡ᤺"
"उ" = "ᤀᤢ"
"ऊ" = "ᤀ᤺ᤢ"
"ऋ" = "ᤖᤢ"
"ॠ" = "ᤖ᤺ᤢ"
"ऌ" = "ᤗᤢ"
"ॡ" = "ᤗ᤺ᤢ"
"ऎ" = ""
"ए" = "ᤀᤣ"
"ऐ" = "ᤀᤤ"
"ऒ" = ""
"ओ" = "ᤀᤥ"
"औ" = "ᤀᤦ"

[vowel_marks]
"ा" = "ᤠ"
"ि" = "ᤡ"
"ी" = "ᤡ᤺"
"ु" = "ᤢ"
"ू" = "᤺ᤢ"
"ृ" = "ᤪᤢ"
"ॄ" = "ᤪ᤺ᤢ"
"ॢ" = "᤻ᤗᤢ"
"ॣ" = "᤻ᤗ᤺ᤢ"
"ॆ" = ""
"े" = "ᤣ"
"ै" = "ᤤ"
"ॊ" = ""
"ो" = "ᤥ"
"ौ" = "ᤦ"

[yogavaahas]
"ं" = "ᤱ"
"ः" = "ᤜ᤻"
"ँ" = "ᤱ"

[virama]
"्" = "᤻"

[consonants]
"क" = "ᤁ"
"ख" = "ᤂ"
"ग" = "ᤃ"
"घ" = "ᤄ"
"ङ" = "ᤅ"
"च" = "ᤆ"
"छ" = "ᤇ"
"ज" = "ᤈ"
"झ" = "ᤈ"
"ञ" = "ᤏ"
"ट" = "ᤋ"
"ठ" = "ᤌ"
"ड" = "ᤍ"
"ढ" = "ᤎ"
"ण" = "ᤏ"
"त" = "ᤋ"
"थ" = "ᤌ"
"द" = "ᤍ"
"ध" = "ᤎ"
"न" = "ᤏ"
"प" = "ᤐ"
"फ" = "ᤑ"
"ब" = "ᤒ"
"भ" = "ᤓ"
"म" = "ᤔ"
"य" = "ᤕ"
"र" = "ᤖ"
"ल" = "ᤗ"
"व" = "ᤘ"
"श" = "ᤙ"
"ष" = "ᤙ"
"स" = "ᤛ"
"ह" = "ᤜ"
"ळ" = "ᤗ"
"क्ष" = "ᤁ᤻ᤙ"
"ज्ञ" = "ᤈ᤻ᤏ"

[symbols]
"०" = "᥆"
"१" = "᥇"
"२" = "᥈"
"३" = "᥉"
"४" = "᥊"
"५" = "᥋"
"६" = "᥌"
"७" = "᥍"
"८" = "᥎"
"९" = "᥏"
"ॐ" = "ᤀᤥᤱ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ᤧ"
