[vowels]
"अ" = "അ"
"आ" = "ആ"
"इ" = "ഇ"
"ई" = "ഈ"
"उ" = "ഉ"
"ऊ" = "ഊ"
"ऋ" = "ഋ"
"ॠ" = "ൠ"
"ऌ" = "ഌ"
"ॡ" = "ൡ"
"ऎ" = "എ"
"ए" = "ഏ"
"ऐ" = "ഐ"
"ऒ" = "ഒ"
"ओ" = "ഓ"
"औ" = "ഔ"

[vowel_marks]
"ा" = "ാ"
"ि" = "ി"
"ी" = "ീ"
"ु" = "ു"
"ू" = "ൂ"
"ृ" = "ൃ"
"ॄ" = "ൄ"
"ॢ" = "ൢ"
"ॣ" = "ൣ"
"ॆ" = "െ"
"े" = "േ"
"ै" = "ൈ"
"ॊ" = "ൊ"
"ो" = "ോ"
"ौ" = "ൌ"

[yogavaahas]
"ं" = "ം"
"ः" = "ഃ"
"ँ" = "ഁ"

[virama]
"्" = "്"

[consonants]
"क" = "ക"
"ख" = "ഖ"
"ग" = "ഗ"
"घ" = "ഘ"
"ङ" = "ങ"
"च" = "ച"
"छ" = "ഛ"
"ज" = "ജ"
"झ" = "ഝ"
"ञ" = "ഞ"
"ट" = "ട"
"ठ" = "ഠ"
"ड" = "ഡ"
"ढ" = "ഢ"
"ण" = "ണ"
"त" = "ത"
"थ" = "ഥ"
"द" = "ദ"
"ध" = "ധ"
"न" = "ന"
"प" = "പ"
"फ" = "ഫ"
"ब" = "ബ"
"भ" = "ഭ"
"म" = "മ"
"य" = "യ"
"र" = "ര"
"ल" = "ല"
"व" = "വ"
"श" = "ശ"
"ष" = "ഷ"
"स" = "സ"
"ह" = "ഹ"
"ळ" = "ള"
"क्ष" = "ക്ഷ"
"ज्ञ" = "ജ്ഞ"

[symbols]
"०" = "൦"
"१" = "൧"
"२" = "൨"
"३" = "൩"
"४" = "൪"
"५" = "൫"
"६" = "൬"
"७" = "൭"
"८" = "൮"
"९" = "൯"
"ॐ" = "ഓം"
"ऽ" = "ഽ"
"।" = "।"
"॥" = "॥"

[extra_consonants]
"क़" = ""
"ख़" = ""
"ग़" = ""
"ज़" = ""
"ड़" = ""
"ढ़" = ""
"फ़" = ""
"य़" = ""
"ऱ" = "റ"
"ऴ" = "ഴ"
