[vowels]
"अ" = "ꯑ"
"आ" = "ꯑꯥ"
"इ" = "ꯏ"
"ई" = "ꯏ"
"उ" = "ꯎ"
"ऊ" = "ꯎ"
"ऋ" = "ꯔꯨ"
"ॠ" = "ꯔꯨ"
"ऌ" = "ꯂꯨ"
"ॡ" = "ꯂꯨ"
"ऎ" = ""
"ए" = "ꯑꯦ"
"ऐ" = "ꯑꯩ"
"ऒ" = ""
"ओ" = "ꯑꯣ"
"औ" = "ꯑꯧ"

[vowel_marks]
"ा" = "ꯥ"
"ि" = "ꯤ"
"ी" = "ꯤ"
"ु" = "ꯨ"
"ू" = "ꯨ"
"ृ" = "꯭ꯔꯨ"
"ॄ" = "꯭ꯔꯨ"
"ॢ" = "꯭ꯂꯨ"
"ॣ" = "꯭ꯂꯨ"
"ॆ" = ""
"े" = "ꯦ"
"ै" = "ꯩ"
"ॊ" = ""
"ो" = "ꯣ"
"ौ" = "ꯧ"

[yogavaahas]
"ं" = "ꯪ"
"ः" = "ꯍ꯭"
"ँ" = "ꯪ"

[virama]
"्" = "꯭"

[consonants]
"क" = "ꯀ"
"ख" = "ꯈ"
"ग" = "ꯒ"
"घ" = "ꯘ"
"ङ" = "ꯉ"
"च" = "ꯆ"
"छ" = "ꯆ"
"ज" = "ꯖ"
"झ" = "ꯓ"
"ञ" = "ꯅ"
"ट" = "ꯇ"
"ठ" = "ꯊ"
"ड" = "ꯗ"
"ढ" = "ꯙ"
"ण" = "ꯅ"
"त" = "ꯇ"
"थ" = "ꯊ"
"द" = "ꯗ"
"ध" = "ꯙ"
"न" = "ꯅ"
"प" = "ꯄ"
"फ" = "ꯐ"
"ब" = "ꯕ"
"भ" = "ꯚ"
"म" = "ꯃ"
"य" = "ꯌ"
"र" = "ꯔ"
"ल" = "ꯂ"
"व" = "ꯋ"
"श" = "ꯁ"
"ष" = "ꯁ"
"स" = "ꯁ"
"ह" = "ꯍ"
"ळ" = "ꯂ"
"क्ष" = "ꯛꯁ"
"ज्ञ" = "ꯖ꯭ꯅ"

[symbols]
"०" = "꯰"
"१" = "꯱"
"२" = "꯲"
"३" = "꯳"
"४" = "꯴"
"५" = "꯵"
"६" = "꯶"
"७" = "꯷"
"८" = "꯸"
"९" = "꯹"
"ॐ" = "ꯑꯣꯪ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ꯦ"
