vowels = [ "ꯑ", "ꯑꯥ", "ꯏ", "ꯏ", "ꯎ", "ꯎ", "ꯔꯨ", "ꯔꯨ", "ꯂꯨ", "ꯂꯨ", "", "ꯑꯦ", "ꯑꯩ", "", "ꯑꯣ", "ꯑꯧ",]
vowel_marks = [ "ꯥ", "ꯤ", "ꯤ", "ꯨ", "ꯨ", "꯭ꯔꯨ", "꯭ꯔꯨ", "꯭ꯂꯨ", "꯭ꯂꯨ", "", "ꯦ", "ꯩ", "", "ꯣ", "ꯧ",]
yogavaahas = [ "ꯪ", "ꯍ꯭", "ꯪ",]
virama = [ "꯭",]
consonants = [ "ꯀ", "ꯈ", "ꯒ", "ꯘ", "ꯉ", "ꯆ", "ꯆ", "ꯖ", "ꯓ", "ꯅ", "ꯇ", "ꯊ", "ꯗ", "ꯙ", "ꯅ", "ꯇ", "ꯊ", "ꯗ", "ꯙ", "ꯅ", "ꯄ", "ꯐ", "ꯕ", "ꯚ", "ꯃ", "ꯌ", "ꯔ", "ꯂ", "ꯋ", "ꯁ", "ꯁ", "ꯁ", "ꯍ", "ꯂ", "ꯛꯁ", "ꯖ꯭ꯅ",]
symbols = [ "꯰", "꯱", "꯲", "꯳", "꯴", "꯵", "꯶", "꯷", "꯸", "꯹", "ꯑꯣꯪ", "'", "।", "॥",]
candra = [ "ꯦ",]
