vowels = [ "ЁС▓П", "ЁС▓ПЁС▓░", "ЁС▓ПЁС▓▒", "ЁС▓ПЁС▓▒ЁС▓░", "ЁС▓ПЁС▓▓", "ЁС▓ПЁС▓▓ЁС▓░", "ЁС▓КЁС▓▒", "ЁС▓КЁС▓▒ЁС▓░", "ЁС▓ЛЁС▓▒", "ЁС▓ЛЁС▓▒ЁС▓░", "", "ЁС▓ПЁС▓│", "ЁС▓ПЁС▓│ЁС▓░", "", "ЁС▓ПЁС▓┤", "ЁС▓ПЁС▓░ЁС▓┤",]
vowel_marks = [ "ЁС▓░", "ЁС▓▒", "ЁС▓▒ЁС▓░", "ЁС▓▓", "ЁС▓▓ЁС▓░", "ЁС▓кЁС▓▒", "ЁС▓кЁС▓▒ЁС▓░", "ЁС▓лЁС▓▒", "ЁС▓лЁС▓▒ЁС▓░", "", "ЁС▓│", "ЁС▓│ЁС▓░", "", "ЁС▓┤", "ЁС▓░ЁС▓┤",]
yogavaahas = [ "ЁС▓╡", "ЁС▓О", "ЁС▓╢",]
virama = [ "",]
consonants = [ "ЁС▒▓", "ЁС▒│", "ЁС▒┤", "ЁС▒┤ЁС▓о", "ЁС▒╡", "ЁС▓В", "ЁС▓Г", "ЁС▓Д", "ЁС▓ДЁС▓о", "ЁС▒╣", "ЁС▒║", "ЁС▒╗", "ЁС▒╝", "ЁС▒╝ЁС▓о", "ЁС▒╜", "ЁС▒║", "ЁС▒╗", "ЁС▒╝", "ЁС▒╝ЁС▓о", "ЁС▒╜", "ЁС▒╛", "ЁС▒┐", "ЁС▓А", "ЁС▓АЁС▓о", "ЁС▓Б", "ЁС▓Й", "ЁС▓К", "ЁС▓Л", "ЁС▓Е", "ЁС▓М", "ЁС▓М", "ЁС▓Н", "ЁС▓О", "ЁС▓Л", "ЁС▒▓ЁС▓м", "ЁС▓ДЁС▓Щ",]
symbols = [ "р╝а", "р╝б", "р╝в", "р╝г", "р╝д", "р╝е", "р╝ж", "р╝з", "р╝и", "р╝й", "ЁС▓ПЁС▓┤ЁС▓╢", "", "ред", "рее",]
candra = [ "ЁС▓│",]
