[vowels]
"рдЕ" = "ЁС▓П"
"рдЖ" = "ЁС▓ПЁС▓░"
"рдЗ" = "ЁС▓ПЁС▓▒"
"рдИ" = "ЁС▓ПЁС▓▒ЁС▓░"
"рдЙ" = "ЁС▓ПЁС▓▓"
"рдК" = "ЁС▓ПЁС▓▓ЁС▓░"
"рдЛ" = "ЁС▓КЁС▓▒"
"реа" = "ЁС▓КЁС▓▒ЁС▓░"
"рдМ" = "ЁС▓ЛЁС▓▒"
"реб" = "ЁС▓ЛЁС▓▒ЁС▓░"
"рдО" = ""
"рдП" = "ЁС▓ПЁС▓│"
"рдР" = "ЁС▓ПЁС▓│ЁС▓░"
"рдТ" = ""
"рдУ" = "ЁС▓ПЁС▓┤"
"рдФ" = "ЁС▓ПЁС▓░ЁС▓┤"

[vowel_marks]
"рд╛" = "ЁС▓░"
"рд┐" = "ЁС▓▒"
"реА" = "ЁС▓▒ЁС▓░"
"реБ" = "ЁС▓▓"
"реВ" = "ЁС▓▓ЁС▓░"
"реГ" = "ЁС▓кЁС▓▒"
"реД" = "ЁС▓кЁС▓▒ЁС▓░"
"рев" = "ЁС▓лЁС▓▒"
"рег" = "ЁС▓лЁС▓▒ЁС▓░"
"реЖ" = ""
"реЗ" = "ЁС▓│"
"реИ" = "ЁС▓│ЁС▓░"
"реК" = ""
"реЛ" = "ЁС▓┤"
"реМ" = "ЁС▓░ЁС▓┤"

[yogavaahas]
"рдВ" = "ЁС▓╡"
"рдГ" = "ЁС▓О"
"рдБ" = "ЁС▓╢"

[virama]
"реН" = ""

[consonants]
"рдХ" = "ЁС▒▓"
"рдЦ" = "ЁС▒│"
"рдЧ" = "ЁС▒┤"
"рдШ" = "ЁС▒┤ЁС▓о"
"рдЩ" = "ЁС▒╡"
"рдЪ" = "ЁС▓В"
"рдЫ" = "ЁС▓Г"
"рдЬ" = "ЁС▓Д"
"рдЭ" = "ЁС▓ДЁС▓о"
"рдЮ" = "ЁС▒╣"
"рдЯ" = "ЁС▒║"
"рда" = "ЁС▒╗"
"рдб" = "ЁС▒╝"
"рдв" = "ЁС▒╝ЁС▓о"
"рдг" = "ЁС▒╜"
"рдд" = "ЁС▒║"
"рде" = "ЁС▒╗"
"рдж" = "ЁС▒╝"
"рдз" = "ЁС▒╝ЁС▓о"
"рди" = "ЁС▒╜"
"рдк" = "ЁС▒╛"
"рдл" = "ЁС▒┐"
"рдм" = "ЁС▓А"
"рдн" = "ЁС▓АЁС▓о"
"рдо" = "ЁС▓Б"
"рдп" = "ЁС▓Й"
"рд░" = "ЁС▓К"
"рд▓" = "ЁС▓Л"
"рд╡" = "ЁС▓Е"
"рд╢" = "ЁС▓М"
"рд╖" = "ЁС▓М"
"рд╕" = "ЁС▓Н"
"рд╣" = "ЁС▓О"
"рд│" = "ЁС▓Л"
"рдХреНрд╖" = "ЁС▒▓ЁС▓м"
"рдЬреНрдЮ" = "ЁС▓ДЁС▓Щ"

[symbols]
"реж" = "р╝а"
"рез" = "р╝б"
"реи" = "р╝в"
"рей" = "р╝г"
"рек" = "р╝д"
"рел" = "р╝е"
"рем" = "р╝ж"
"рен" = "р╝з"
"рео" = "р╝и"
"реп" = "р╝й"
"реР" = "ЁС▓ПЁС▓┤ЁС▓╢"
"рд╜" = ""
"ред" = "ред"
"рее" = "рее"

[candra]
"реЕ" = "ЁС▓│"
