[vowels]
"рдЕ" = "ЁСША"
"рдЖ" = "ЁСШБ"
"рдЗ" = "ЁСШГ"
"рдИ" = "ЁСШГ"
"рдЙ" = "ЁСШД"
"рдК" = "ЁСШД"
"рдЛ" = "ЁСШиЁСШ▓"
"реа" = "ЁСШиЁСШ▓"
"рдМ" = "ЁСШйЁСШ▓"
"реб" = "ЁСШйЁСШ▓"
"рдО" = ""
"рдП" = "ЁСШК"
"рдР" = "ЁСШЛ"
"рдТ" = ""
"рдУ" = "ЁСШМ"
"рдФ" = "ЁСШН"

[vowel_marks]
"рд╛" = "ЁСШ░"
"рд┐" = "ЁСШ▓"
"реА" = "ЁСШ▓"
"реБ" = "ЁСШ│"
"реВ" = "ЁСШ│"
"реГ" = "ЁСШ┐ЁСШиЁСШ▓"
"реД" = "ЁСШ┐ЁСШиЁСШ▓"
"рев" = "ЁСШ┐ЁСШйЁСШ▓"
"рег" = "ЁСШ┐ЁСШйЁСШ▓"
"реЖ" = ""
"реЗ" = "ЁСШ╣"
"реИ" = "ЁСШ║"
"реК" = ""
"реЛ" = "ЁСШ╗"
"реМ" = "ЁСШ╝"

[yogavaahas]
"рдВ" = "ЁСШ╜"
"рдГ" = "ЁСШ╛"
"рдБ" = "ЁСШ╜"

[virama]
"реН" = "ЁСШ┐"

[consonants]
"рдХ" = "ЁСШО"
"рдЦ" = "ЁСШП"
"рдЧ" = "ЁСШР"
"рдШ" = "ЁСШС"
"рдЩ" = "ЁСШТ"
"рдЪ" = "ЁСШУ"
"рдЫ" = "ЁСШФ"
"рдЬ" = "ЁСШХ"
"рдЭ" = "ЁСШЦ"
"рдЮ" = "ЁСШЧ"
"рдЯ" = "ЁСШШ"
"рда" = "ЁСШЩ"
"рдб" = "ЁСШЪ"
"рдв" = "ЁСШЫ"
"рдг" = "ЁСШЬ"
"рдд" = "ЁСШЭ"
"рде" = "ЁСШЮ"
"рдж" = "ЁСШЯ"
"рдз" = "ЁСШа"
"рди" = "ЁСШб"
"рдк" = "ЁСШв"
"рдл" = "ЁСШг"
"рдм" = "ЁСШд"
"рдн" = "ЁСШе"
"рдо" = "ЁСШж"
"рдп" = "ЁСШз"
"рд░" = "ЁСШи"
"рд▓" = "ЁСШй"
"рд╡" = "ЁСШк"
"рд╢" = "ЁСШл"
"рд╖" = "ЁСШм"
"рд╕" = "ЁСШн"
"рд╣" = "ЁСШо"
"рд│" = "ЁСШп"
"рдХреНрд╖" = "ЁСШОЁСШ┐ЁСШм"
"рдЬреНрдЮ" = "ЁСШХЁСШ┐ЁСШЧ"

[symbols]
"реж" = "ЁСЩР"
"рез" = "ЁСЩС"
"реи" = "ЁСЩТ"
"рей" = "ЁСЩУ"
"рек" = "ЁСЩФ"
"рел" = "ЁСЩХ"
"рем" = "ЁСЩЦ"
"рен" = "ЁСЩЧ"
"рео" = "ЁСЩШ"
"реп" = "ЁСЩЩ"
"реР" = "ЁСШМЁСШ╜"
"рд╜" = "рд╜"
"ред" = "ред"
"рее" = "рее"

[candra]
"реЕ" = "ЁСЩА"
