vowels = [ "အ", "အာ", "ဣ", "ဣဳ", "ဥ", "ဥူ", "ၒ", "ၓ", "ၔ", "ၕ", "", "ဨ", "အဲ", "", "ဩ", "ဪ",]
vowel_marks = [ "ာ", "ိ", "ဳ", "ု", "ူ", "ၖ", "ၗ", "ၘ", "ၙ", "", "ေ", "ဲ", "", "ော", "ော်",]
yogavaahas = [ "ံ", "း", "ံ",]
virama = [ "်",]
consonants = [ "က", "ခ", "ဂ", "ဃ", "ၚ", "စ", "ဆ", "ဇ", "ၛ", "ည", "ဋ", "ဌ", "ဍ", "ဎ", "ဏ", "တ", "ထ", "ဒ", "ဓ", "န", "ပ", "ဖ", "ဗ", "ဘ", "မ", "ယ", "ရ", "လ", "ဝ", "ၐ", "ၑ", "သ", "ဟ", "ဠ", "က္ၑ", "ဇ္ည",]
symbols = [ "၀", "၁", "၂", "၃", "၄", "၅", "၆", "၇", "၈", "၉", "ဩံ", "'", "।", "॥",]
candra = [ "ေ",]
