[vowels]
"अ" = "အ"
"आ" = "အာ"
"इ" = "ဣ"
"ई" = "ဣဳ"
"उ" = "ဥ"
"ऊ" = "ဥူ"
"ऋ" = "ၒ"
"ॠ" = "ၓ"
"ऌ" = "ၔ"
"ॡ" = "ၕ"
"ऎ" = ""
"ए" = "ဨ"
"ऐ" = "အဲ"
"ऒ" = ""
"ओ" = "ဩ"
"औ" = "ဪ"

[vowel_marks]
"ा" = "ာ"
"ि" = "ိ"
"ी" = "ဳ"
"ु" = "ု"
"ू" = "ူ"
"ृ" = "ၖ"
"ॄ" = "ၗ"
"ॢ" = "ၘ"
"ॣ" = "ၙ"
"ॆ" = ""
"े" = "ေ"
"ै" = "ဲ"
"ॊ" = ""
"ो" = "ော"
"ौ" = "ော်"

[yogavaahas]
"ं" = "ံ"
"ः" = "း"
"ँ" = "ံ"

[virama]
"्" = "်"

[consonants]
"क" = "က"
"ख" = "ခ"
"ग" = "ဂ"
"घ" = "ဃ"
"ङ" = "ၚ"
"च" = "စ"
"छ" = "ဆ"
"ज" = "ဇ"
"झ" = "ၛ"
"ञ" = "ည"
"ट" = "ဋ"
"ठ" = "ဌ"
"ड" = "ဍ"
"ढ" = "ဎ"
"ण" = "ဏ"
"त" = "တ"
"थ" = "ထ"
"द" = "ဒ"
"ध" = "ဓ"
"न" = "န"
"प" = "ပ"
"फ" = "ဖ"
"ब" = "ဗ"
"भ" = "ဘ"
"म" = "မ"
"य" = "ယ"
"र" = "ရ"
"ल" = "လ"
"व" = "ဝ"
"श" = "ၐ"
"ष" = "ၑ"
"स" = "သ"
"ह" = "ဟ"
"ळ" = "ဠ"
"क्ष" = "က္ၑ"
"ज्ञ" = "ဇ္ည"

[symbols]
"०" = "၀"
"१" = "၁"
"२" = "၂"
"३" = "၃"
"४" = "၄"
"५" = "၅"
"६" = "၆"
"७" = "၇"
"८" = "၈"
"९" = "၉"
"ॐ" = "ဩံ"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ေ"
