vowels = [ "ᱚ", "ᱟ", "ᱤ", "ᱤᱻ", "ᱩ", "ᱩᱻ", "ᱨᱩ", "ᱨᱩᱻ", "ᱞᱩ", "ᱞᱩᱻ", "ᱮᱹ", "ᱮ", "ᱚᱤ", "ᱳ", "ᱳ", "ᱚᱩ",]
vowel_marks = [ "ᱟ", "ᱤ", "ᱤᱻ", "ᱩ", "ᱩᱻ", "ᱨᱩ", "ᱨᱩᱻ", "ᱞᱩ", "ᱞᱩᱻ", "ᱮᱹ", "ᱮ", "ᱚᱤ", "ᱳ", "ᱳ", "ᱚᱩ",]
yogavaahas = [ "ᱝ", "ᱷ", "ᱸ",]
virama = [ "",]
consonants = [ "ᱠᱚ", "ᱠᱷᱚ", "ᱜᱚ", "ᱜᱷᱚ", "ᱶᱚ", "ᱪᱚ", "ᱪᱷᱚ", "ᱡᱚ", "ᱡᱷᱚ", "ᱧᱚ", "ᱴᱚ", "ᱴᱷᱚ", "ᱰᱚ", "ᱰᱷᱚ", "ᱬᱚ", "ᱛᱚ", "ᱛᱷᱚ", "ᱫᱚ", "ᱫᱷᱚ", "ᱱᱚ", "ᱯᱚ", "ᱯᱷᱚ", "ᱵᱚ", "ᱵᱷᱚ", "ᱢᱚ", "ᱭᱚ", "ᱨᱚ", "ᱞᱚ", "ᱣᱚ", "ᱥᱚ", "ᱥᱚ", "ᱥᱚ", "ᱦᱚ", "ᱞᱚ", "ᱠᱥᱚ", "ᱡᱧᱚ",]
symbols = [ "᱐", "᱑", "᱒", "᱓", "᱔", "᱕", "᱖", "᱗", "᱘", "᱙", "ᱳᱸ", "'", "᱾", "᱿",]
candra = [ "ᱚᱹ",]
extra_consonants = [ "ᱠᱚ", "ᱠᱷᱚ", "ᱜᱚ", "ᱡᱚ", "ᱲᱚ", "ᱲᱷᱚ", "ᱯᱚ", "ᱭᱚ", "ᱨᱚ",]
