[vowels]
"अ" = "ᱚ"
"आ" = "ᱟ"
"इ" = "ᱤ"
"ई" = "ᱤᱻ"
"उ" = "ᱩ"
"ऊ" = "ᱩᱻ"
"ऋ" = "ᱨᱩ"
"ॠ" = "ᱨᱩᱻ"
"ऌ" = "ᱞᱩ"
"ॡ" = "ᱞᱩᱻ"
"ऎ" = "ᱮᱹ"
"ए" = "ᱮ"
"ऐ" = "ᱚᱤ"
"ऒ" = "ᱳ"
"ओ" = "ᱳ"
"औ" = "ᱚᱩ"

[vowel_marks]
"ा" = "ᱟ"
"ि" = "ᱤ"
"ी" = "ᱤᱻ"
"ु" = "ᱩ"
"ू" = "ᱩᱻ"
"ृ" = "ᱨᱩ"
"ॄ" = "ᱨᱩᱻ"
"ॢ" = "ᱞᱩ"
"ॣ" = "ᱞᱩᱻ"
"ॆ" = "ᱮᱹ"
"े" = "ᱮ"
"ै" = "ᱚᱤ"
"ॊ" = "ᱳ"
"ो" = "ᱳ"
"ौ" = "ᱚᱩ"

[yogavaahas]
"ं" = "ᱝ"
"ः" = "ᱷ"
"ँ" = "ᱸ"

[virama]
"्" = ""

[consonants]
"क" = "ᱠᱚ"
"ख" = "ᱠᱷᱚ"
"ग" = "ᱜᱚ"
"घ" = "ᱜᱷᱚ"
"ङ" = "ᱶᱚ"
"च" = "ᱪᱚ"
"छ" = "ᱪᱷᱚ"
"ज" = "ᱡᱚ"
"झ" = "ᱡᱷᱚ"
"ञ" = "ᱧᱚ"
"ट" = "ᱴᱚ"
"ठ" = "ᱴᱷᱚ"
"ड" = "ᱰᱚ"
"ढ" = "ᱰᱷᱚ"
"ण" = "ᱬᱚ"
"त" = "ᱛᱚ"
"थ" = "ᱛᱷᱚ"
"द" = "ᱫᱚ"
"ध" = "ᱫᱷᱚ"
"न" = "ᱱᱚ"
"प" = "ᱯᱚ"
"फ" = "ᱯᱷᱚ"
"ब" = "ᱵᱚ"
"भ" = "ᱵᱷᱚ"
"म" = "ᱢᱚ"
"य" = "ᱭᱚ"
"र" = "ᱨᱚ"
"ल" = "ᱞᱚ"
"व" = "ᱣᱚ"
"श" = "ᱥᱚ"
"ष" = "ᱥᱚ"
"स" = "ᱥᱚ"
"ह" = "ᱦᱚ"
"ळ" = "ᱞᱚ"
"क्ष" = "ᱠᱥᱚ"
"ज्ञ" = "ᱡᱧᱚ"

[symbols]
"०" = "᱐"
"१" = "᱑"
"२" = "᱒"
"३" = "᱓"
"४" = "᱔"
"५" = "᱕"
"६" = "᱖"
"७" = "᱗"
"८" = "᱘"
"९" = "᱙"
"ॐ" = "ᱳᱸ"
"ऽ" = "'"
"।" = "᱾"
"॥" = "᱿"

[candra]
"ॅ" = "ᱚᱹ"

[extra_consonants]
"क़" = "ᱠᱚ"
"ख़" = "ᱠᱷᱚ"
"ग़" = "ᱜᱚ"
"ज़" = "ᱡᱚ"
"ड़" = "ᱲᱚ"
"ढ़" = "ᱲᱷᱚ"
"फ़" = "ᱯᱚ"
"य़" = "ᱭᱚ"
"ऱ" = "ᱨᱚ"
