vowels = [ "ꡝ", "ꡝꡖ", "ꡞ", "ꡞꡖ", "ꡟ", "ꡟꡖ", "ꡘꡞ", "ꡘꡖꡞ", "ꡙꡞ", "ꡙꡖꡞ", "", "ꡠ", "ꡠꡖ", "", "ꡡ", "ꡡꡖ",]
vowel_marks = [ "ꡖ", "ꡞ", "ꡖꡞ", "ꡟ", "ꡖꡟ", "ꡱꡞ", "ꡖꡱꡞ", "ꡙꡞ", "ꡙꡖꡞ", "", "ꡠ", "ꡖꡠ", "", "ꡡ", "ꡖꡡ",]
yogavaahas = [ "ꡳ", "ꡜ", "ꡳ",]
virama = [ "",]
consonants = [ "ꡀ", "ꡁ", "ꡂ", "ꡂꡜ", "ꡃ", "ꡐ", "ꡑ", "ꡒ", "ꡒꡜ", "ꡇ", "ꡩ", "ꡪ", "ꡫ", "ꡫꡜ", "ꡬ", "ꡈ", "ꡉ", "ꡊ", "ꡊꡜ", "ꡋ", "ꡌ", "ꡍ", "ꡎ", "ꡎꡜ", "ꡏ", "ꡗ", "ꡘ", "ꡙ", "ꡓ", "ꡚ", "ꡚ", "ꡛ", "ꡜ", "ꡙ", "ꡀꡚ", "ꡒꡇ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ꡳꡡ", "", "।", "॥",]
candra = [ "ꡠ",]
