[vowels]
"अ" = "अ"
"आ" = "आ"
"इ" = "इ"
"ई" = "ई"
"उ" = "उ"
"ऊ" = "ऊ"
"ऋ" = "ऋ"
"ॠ" = "ॠ"
"ऌ" = "ऌ"
"ॡ" = "ॡ"
"ऎ" = ""
"ए" = "ए"
"ऐ" = "ऐ"
"ऒ" = ""
"ओ" = "ओ"
"औ" = "औ"

[vowel_marks]
"ा" = "ा"
"ि" = "ि"
"ी" = "ी"
"ु" = "ु"
"ू" = "ू"
"ृ" = "ृ"
"ॄ" = "ॄ"
"ॢ" = "ॢ"
"ॣ" = "ॣ"
"ॆ" = ""
"े" = "े"
"ै" = "ै"
"ॊ" = ""
"ो" = "ो"
"ौ" = "ौ"

[yogavaahas]
"ं" = "ं"
"ः" = "ः"
"ँ" = "ँ"

[virama]
"्" = "्"

[consonants]
"क" = "क"
"ख" = "ख"
"ग" = "ग"
"घ" = "घ"
"ङ" = "ङ"
"च" = "च"
"छ" = "छ"
"ज" = "ज"
"झ" = "झ"
"ञ" = "ञ"
"ट" = "ट"
"ठ" = "ठ"
"ड" = "ड"
"ढ" = "ढ"
"ण" = "ण"
"त" = "त"
"थ" = "थ"
"द" = "द"
"ध" = "ध"
"न" = "न"
"प" = "प"
"फ" = "फ"
"ब" = "ब"
"भ" = "भ"
"म" = "म"
"य" = "य"
"र" = "र"
"ल" = "ल"
"व" = "व"
"श" = "श"
"ष" = "ष"
"स" = "स"
"ह" = "ह"
"ळ" = "ल"
"क्ष" = "क्ष"
"ज्ञ" = "ज्ञ"

[symbols]
"०" = "०"
"१" = "१"
"२" = "२"
"३" = "३"
"४" = "४"
"५" = "५"
"६" = "६"
"७" = "७"
"८" = "८"
"९" = "९"
"ॐ" = "ॐ"
"ऽ" = "ऽ"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "े"
