vowels = [ "अ", "आ", "इ", "ई", "उ", "ऊ", "ऋ", "ॠ", "ऌ", "ॡ", "", "ए", "ऐ", "", "ओ", "औ",]
vowel_marks = [ "ा", "ि", "ी", "ु", "ू", "ृ", "ॄ", "ॢ", "ॣ", "", "े", "ै", "", "ो", "ौ",]
yogavaahas = [ "ं", "ः", "ँ",]
virama = [ "्",]
consonants = [ "क", "ख", "ग", "घ", "ङ", "च", "छ", "ज", "झ", "ञ", "ट", "ठ", "ड", "ढ", "ण", "त", "थ", "द", "ध", "न", "प", "फ", "ब", "भ", "म", "य", "र", "ल", "व", "श", "ष", "स", "ह", "ल", "क्ष", "ज्ञ",]
symbols = [ "०", "१", "२", "३", "४", "५", "६", "७", "८", "९", "ॐ", "ऽ", "।", "॥",]
candra = [ "े",]
