[vowels]
"рдЕ" = "ЁР┤АЁР┤Э"
"рдЖ" = "ЁР┤АЁР┤ЭЁР┤д"
"рдЗ" = "ЁР┤АЁР┤Ю"
"рдИ" = "ЁР┤АЁР┤ЮЁР┤д"
"рдЙ" = "ЁР┤АЁР┤Я"
"рдК" = "ЁР┤АЁР┤ЯЁР┤д"
"рдЛ" = "ЁР┤МЁР┤Я"
"реа" = "ЁР┤МЁР┤ЯЁР┤д"
"рдМ" = "ЁР┤УЁР┤Я"
"реб" = "ЁР┤УЁР┤ЯЁР┤д"
"рдО" = ""
"рдП" = "ЁР┤АЁР┤аЁР┤д"
"рдР" = "ЁР┤АЁР┤ЭЁР┤Щ"
"рдТ" = ""
"рдУ" = "ЁР┤АЁР┤бЁР┤д"
"рдФ" = "ЁР┤АЁР┤ЭЁР┤Ч"

[vowel_marks]
"рд╛" = "ЁР┤АЁР┤ЭЁР┤д"
"рд┐" = "ЁР┤АЁР┤Ю"
"реА" = "ЁР┤АЁР┤ЮЁР┤д"
"реБ" = "ЁР┤АЁР┤Я"
"реВ" = "ЁР┤АЁР┤ЯЁР┤д"
"реГ" = "ЁР┤МЁР┤Я"
"реД" = "ЁР┤МЁР┤ЯЁР┤д"
"рев" = "ЁР┤УЁР┤Я"
"рег" = "ЁР┤УЁР┤ЯЁР┤д"
"реЖ" = ""
"реЗ" = "ЁР┤АЁР┤аЁР┤д"
"реИ" = "ЁР┤АЁР┤ЭЁР┤Щ"
"реК" = ""
"реЛ" = "ЁР┤АЁР┤бЁР┤д"
"реМ" = "ЁР┤АЁР┤ЭЁР┤Ч"

[yogavaahas]
"рдВ" = "ЁР┤г"
"рдГ" = "ЁР┤З"
"рдБ" = "ЁР┤г"

[virama]
"реН" = ""

[consonants]
"рдХ" = "ЁР┤СЁР┤Э"
"рдЦ" = "ЁР┤СЁР┤Э"
"рдЧ" = "ЁР┤ТЁР┤Э"
"рдШ" = "ЁР┤ТЁР┤Э"
"рдЩ" = "ЁР┤ЪЁР┤Э"
"рдЪ" = "ЁР┤ЖЁР┤Э"
"рдЫ" = "ЁР┤ЖЁР┤Э"
"рдЬ" = "ЁР┤ЕЁР┤Э"
"рдЭ" = "ЁР┤ЕЁР┤Э"
"рдЮ" = "ЁР┤ЫЁР┤Э"
"рдЯ" = "ЁР┤ДЁР┤Э"
"рда" = "ЁР┤ДЁР┤Э"
"рдб" = "ЁР┤ЛЁР┤Э"
"рдв" = "ЁР┤ЛЁР┤Э"
"рдг" = "ЁР┤ХЁР┤Э"
"рдд" = "ЁР┤ГЁР┤Э"
"рде" = "ЁР┤ГЁР┤Э"
"рдж" = "ЁР┤КЁР┤Э"
"рдз" = "ЁР┤КЁР┤Э"
"рди" = "ЁР┤ХЁР┤Э"
"рдк" = "ЁР┤ВЁР┤Э"
"рдл" = "ЁР┤ВЁР┤Э"
"рдм" = "ЁР┤БЁР┤Э"
"рдн" = "ЁР┤БЁР┤Э"
"рдо" = "ЁР┤ФЁР┤Э"
"рдп" = "ЁР┤ШЁР┤Э"
"рд░" = "ЁР┤МЁР┤Э"
"рд▓" = "ЁР┤УЁР┤Э"
"рд╡" = "ЁР┤ЦЁР┤Э"
"рд╢" = "ЁР┤РЁР┤Э"
"рд╖" = "ЁР┤РЁР┤Э"
"рд╕" = "ЁР┤ПЁР┤Э"
"рд╣" = "ЁР┤ЗЁР┤Э"
"рд│" = "ЁР┤УЁР┤Э"
"рдХреНрд╖" = "ЁР┤СЁР┤РЁР┤Э"
"рдЬреНрдЮ" = "ЁР┤ЕЁР┤ЫЁР┤Э"

[symbols]
"реж" = "ЁР┤░"
"рез" = "ЁР┤▒"
"реи" = "ЁР┤▓"
"рей" = "ЁР┤│"
"рек" = "ЁР┤┤"
"рел" = "ЁР┤╡"
"рем" = "ЁР┤╢"
"рен" = "ЁР┤╖"
"рео" = "ЁР┤╕"
"реп" = "ЁР┤╣"
"реР" = "ЁР┤АЁР┤АЁР┤бЁР┤┤ЁР┤Ф"
"рд╜" = ""
"ред" = "ред"
"рее" = "рее"

[candra]
"реЕ" = "ЁР┤АЁР┤а"
