vowels = [ "အ", "အႃ", "အိ", "အီ", "အု", "အူ", "အၖ", "အၗ", "အၘ", "အၙ", "အေ", "အေ", "အႆ", "အေႃ", "အေႃ", "အဝ်",]
vowel_marks = [ "ႃ", "ိ", "ီ", "ု", "ူ", "ၖ", "ၗ", "ၘ", "ၙ", "ေ", "ေ", "ႆ", "ေႃ", "ေႃ", "ဝ်",]
yogavaahas = [ "ံ", "း", "ံ",]
virama = [ "်",]
consonants = [ "ၵ", "ၶ", "ၷ", "ꧠ", "င", "ၸ", "ꧡ", "ꩡ", "ꧢ", "ၺ", "ꩦ", "ꩧ", "ꩨ", "ꩩ", "ꧣ", "တ", "ထ", "ၻ", "ꩪ", "ၼ", "ပ", "ၽ", "ၿ", "ꧤ", "မ", "ယ", "ရ", "လ", "ဝ", "ၐ", "ၑ", "သ", "ႁ", "ꩮ", "ၵ်ၑ", "ꩡ်ၺ",]
symbols = [ "႐", "႑", "႒", "႓", "႔", "႕", "႖", "႗", "႘", "႙", "အေႃံ", "'", "၊", "။",]
candra = [ "ႄ",]
extra_consonants = [ "ၵ", "ၶ", "ၷ", "ၹ", "ꩨ", "ꩩ", "ၾ", "ယ", "ရ",]
