[vowels]
"अ" = "အ"
"आ" = "အႃ"
"इ" = "အိ"
"ई" = "အီ"
"उ" = "အု"
"ऊ" = "အူ"
"ऋ" = "အၖ"
"ॠ" = "အၗ"
"ऌ" = "အၘ"
"ॡ" = "အၙ"
"ऎ" = "အေ"
"ए" = "အေ"
"ऐ" = "အႆ"
"ऒ" = "အေႃ"
"ओ" = "အေႃ"
"औ" = "အဝ်"

[vowel_marks]
"ा" = "ႃ"
"ि" = "ိ"
"ी" = "ီ"
"ु" = "ု"
"ू" = "ူ"
"ृ" = "ၖ"
"ॄ" = "ၗ"
"ॢ" = "ၘ"
"ॣ" = "ၙ"
"ॆ" = "ေ"
"े" = "ေ"
"ै" = "ႆ"
"ॊ" = "ေႃ"
"ो" = "ေႃ"
"ौ" = "ဝ်"

[yogavaahas]
"ं" = "ံ"
"ः" = "း"
"ँ" = "ံ"

[virama]
"्" = "်"

[consonants]
"क" = "ၵ"
"ख" = "ၶ"
"ग" = "ၷ"
"घ" = "ꧠ"
"ङ" = "င"
"च" = "ၸ"
"छ" = "ꧡ"
"ज" = "ꩡ"
"झ" = "ꧢ"
"ञ" = "ၺ"
"ट" = "ꩦ"
"ठ" = "ꩧ"
"ड" = "ꩨ"
"ढ" = "ꩩ"
"ण" = "ꧣ"
"त" = "တ"
"थ" = "ထ"
"द" = "ၻ"
"ध" = "ꩪ"
"न" = "ၼ"
"प" = "ပ"
"फ" = "ၽ"
"ब" = "ၿ"
"भ" = "ꧤ"
"म" = "မ"
"य" = "ယ"
"र" = "ရ"
"ल" = "လ"
"व" = "ဝ"
"श" = "ၐ"
"ष" = "ၑ"
"स" = "သ"
"ह" = "ႁ"
"ळ" = "ꩮ"
"क्ष" = "ၵ်ၑ"
"ज्ञ" = "ꩡ်ၺ"

[symbols]
"०" = "႐"
"१" = "႑"
"२" = "႒"
"३" = "႓"
"४" = "႔"
"५" = "႕"
"६" = "႖"
"७" = "႗"
"८" = "႘"
"९" = "႙"
"ॐ" = "အေႃံ"
"ऽ" = "'"
"।" = "၊"
"॥" = "။"

[candra]
"ॅ" = "ႄ"

[extra_consonants]
"क़" = "ၵ"
"ख़" = "ၶ"
"ग़" = "ၷ"
"ज़" = "ၹ"
"ड़" = "ꩨ"
"ढ़" = "ꩩ"
"फ़" = "ၾ"
"य़" = "ယ"
"ऱ" = "ရ"
