[vowels]
"अ" = "අ"
"आ" = "ආ"
"इ" = "ඉ"
"ई" = "ඊ"
"उ" = "උ"
"ऊ" = "ඌ"
"ऋ" = "ඍ"
"ॠ" = "ඎ"
"ऌ" = "ඏ"
"ॡ" = "ඐ"
"ऎ" = "එ"
"ए" = "ඒ"
"ऐ" = "ඓ"
"ऒ" = "ඔ"
"ओ" = "ඕ"
"औ" = "ඖ"

[vowel_marks]
"ा" = "ා"
"ि" = "ි"
"ी" = "ී"
"ु" = "ු"
"ू" = "ූ"
"ृ" = "ෘ"
"ॄ" = "ෲ"
"ॢ" = "ෟ"
"ॣ" = "ෳ"
"ॆ" = "ෙ"
"े" = "ේ"
"ै" = "ෛ"
"ॊ" = "ො"
"ो" = "ෝ"
"ौ" = "ෞ"

[yogavaahas]
"ं" = "ං"
"ः" = "ඃ"

[virama]
"्" = "්"

[consonants]
"क" = "ක"
"ख" = "ඛ"
"ग" = "ග"
"घ" = "ඝ"
"ङ" = "ඞ"
"च" = "ච"
"छ" = "ඡ"
"ज" = "ජ"
"झ" = "ඣ"
"ञ" = "ඤ"
"ट" = "ට"
"ठ" = "ඨ"
"ड" = "ඩ"
"ढ" = "ඪ"
"ण" = "ණ"
"त" = "ත"
"थ" = "ථ"
"द" = "ද"
"ध" = "ධ"
"न" = "න"
"प" = "ප"
"फ" = "ඵ"
"ब" = "බ"
"भ" = "භ"
"म" = "ම"
"य" = "ය"
"र" = "ර"
"ल" = "ල"
"व" = "ව"
"श" = "ශ"
"ष" = "ෂ"
"स" = "ස"
"ह" = "හ"
"ळ" = "ළ"
"क्ष" = "ක්\u200dෂ"
"ज्ञ" = "ඥ"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "ඕං"
"ऽ" = "(අ)"
"।" = "."
"॥" = ".."

[candra]
"ॅ" = "ැ"
