[vowels]
"अ" = "အ"
"आ" = "အႃ"
"इ" = "အိ"
"ई" = "အီ"
"उ" = "အု"
"ऊ" = "အူ"
"ऋ" = "ꩺိ"
"ॠ" = "ꩺီ"
"ऌ" = "လိ"
"ॡ" = "လီ"
"ऎ" = "အေ"
"ए" = "အေ"
"ऐ" = "အႆ"
"ऒ" = "အေႃ"
"ओ" = "အေႃ"
"औ" = "အဝ်"

[vowel_marks]
"ा" = "ႃ"
"ि" = "ိ"
"ी" = "ီ"
"ु" = "ု"
"ू" = "ူ"
"ृ" = "ြိ"
"ॄ" = "ြီ"
"ॢ" = "်လိ"
"ॣ" = "်လီ"
"ॆ" = "ေ"
"े" = "ေ"
"ै" = "ႆ"
"ॊ" = "ေႃ"
"ो" = "ေႃ"
"ौ" = "ဝ်"

[yogavaahas]
"ं" = "ံ"
"ः" = "း"
"ँ" = "ံ"

[virama]
"्" = "်"

[consonants]
"क" = "က"
"ख" = "ၵ"
"ग" = "ꧩ"
"घ" = "ꧪ"
"ङ" = "င"
"च" = "ၸ"
"छ" = "ꩬ"
"ज" = "ꧫ"
"झ" = "ꧬ"
"ञ" = "ꧧ"
"ट" = "ꩦ"
"ठ" = "ꩧ"
"ड" = "ꧭ"
"ढ" = "ꧮ"
"ण" = "ꧯ"
"त" = "တ"
"थ" = "ထ"
"द" = "ꧻ"
"ध" = "ꧼ"
"न" = "ꩫ"
"प" = "ပ"
"फ" = "ꧤ"
"ब" = "ꧽ"
"भ" = "ꧾ"
"म" = "မ"
"य" = "ယ"
"र" = "ꩺ"
"ल" = "လ"
"व" = "ဝ"
"श" = "ꧬ"
"ष" = "ꧬ"
"स" = "ꧬ"
"ह" = "ၯ"
"ळ" = "ꧺ"
"क्ष" = "က်ꧬ"
"ज्ञ" = "ꧫ်ꧧ"

[symbols]
"०" = "꧰"
"१" = "꧱"
"२" = "꧲"
"३" = "꧳"
"४" = "꧴"
"५" = "꧵"
"६" = "꧶"
"७" = "꧷"
"८" = "꧸"
"९" = "꧹"
"ॐ" = "အေႃံ"
"ऽ" = "'"
"।" = "၊"
"॥" = "။"

[candra]
"ॅ" = "ႄ"

[extra_consonants]
"क़" = "က"
"ख़" = "ၵ"
"ग़" = "ꧩ"
"ज़" = "ꧫ"
"ड़" = "ꧭ"
"ढ़" = "ꧮ"
"फ़" = "ꧨ"
"य़" = "ယ"
"ऱ" = "ꩺ"
