vowels = [ "အ", "အႃ", "အိ", "အီ", "အု", "အူ", "ꩺိ", "ꩺီ", "လိ", "လီ", "အေ", "အေ", "အႆ", "အေႃ", "အေႃ", "အဝ်",]
vowel_marks = [ "ႃ", "ိ", "ီ", "ု", "ူ", "ြိ", "ြီ", "်လိ", "်လီ", "ေ", "ေ", "ႆ", "ေႃ", "ေႃ", "ဝ်",]
yogavaahas = [ "ံ", "း", "ံ",]
virama = [ "်",]
consonants = [ "က", "ၵ", "ꧩ", "ꧪ", "င", "ၸ", "ꩬ", "ꧫ", "ꧬ", "ꧧ", "ꩦ", "ꩧ", "ꧭ", "ꧮ", "ꧯ", "တ", "ထ", "ꧻ", "ꧼ", "ꩫ", "ပ", "ꧤ", "ꧽ", "ꧾ", "မ", "ယ", "ꩺ", "လ", "ဝ", "ꧬ", "ꧬ", "ꧬ", "ၯ", "ꧺ", "က်ꧬ", "ꧫ်ꧧ",]
symbols = [ "꧰", "꧱", "꧲", "꧳", "꧴", "꧵", "꧶", "꧷", "꧸", "꧹", "အေႃံ", "'", "၊", "။",]
candra = [ "ႄ",]
extra_consonants = [ "က", "ၵ", "ꧩ", "ꧫ", "ꧭ", "ꧮ", "ꧨ", "ယ", "ꩺ",]
