[vowels]
"अ" = "அ"
"आ" = "ஆ"
"इ" = "இ"
"ई" = "ஈ"
"उ" = "உ"
"ऊ" = "ஊ"
"ऋ" = "ருʼ"
"ॠ" = "ரூʼ"
"ऌ" = "லுʼ"
"ॡ" = "லூʼ"
"ऎ" = "எ"
"ए" = "ஏ"
"ऐ" = "ஐ"
"ऒ" = "ஒ"
"ओ" = "ஓ"
"औ" = "ஔ"

[vowel_marks]
"ा" = "ா"
"ि" = "ி"
"ी" = "ீ"
"ु" = "ு"
"ू" = "ூ"
"ृ" = "்ருʼ"
"ॄ" = "்ரூʼ"
"ॢ" = "்லுʼ"
"ॣ" = "்லூʼ"
"ॆ" = "ெ"
"े" = "ே"
"ै" = "ை"
"ॊ" = "ொ"
"ो" = "ோ"
"ौ" = "ௌ"

[yogavaahas]
"ं" = "ம்ʼ"
"ः" = "꞉"
"ँ" = "ம்ˮ"

[virama]
"्" = "்"

[consonants]
"क" = "க"
"ख" = "க²"
"ग" = "க³"
"घ" = "க⁴"
"ङ" = "ங"
"च" = "ச"
"छ" = "ச²"
"ज" = "ஜ"
"झ" = "ஜ²"
"ञ" = "ஞ"
"ट" = "ட"
"ठ" = "ட²"
"ड" = "ட³"
"ढ" = "ட⁴"
"ण" = "ண"
"त" = "த"
"थ" = "த²"
"द" = "த³"
"ध" = "த⁴"
"न" = "ந"
"प" = "ப"
"फ" = "ப²"
"ब" = "ப³"
"भ" = "ப⁴"
"म" = "ம"
"य" = "ய"
"र" = "ர"
"ल" = "ல"
"व" = "வ"
"श" = "ஶ"
"ष" = "ஷ"
"स" = "ஸ"
"ह" = "ஹ"
"ळ" = "ள"
"क्ष" = "க்ஷ"
"ज्ञ" = "ஜ்ஞ"

[symbols]
"०" = "௦"
"१" = "௧"
"२" = "௨"
"३" = "௩"
"४" = "௪"
"५" = "௫"
"६" = "௬"
"७" = "௭"
"८" = "௮"
"९" = "௯"
"ॐ" = "ௐ"
"ऽ" = "(அ)"
"।" = "."
"॥" = ".."

[candra]
"ॅ" = "ே"

[extra_consonants]
"क़" = "ஃʼக"
"ख़" = "ஃக²"
"ग़" = "ஃக³"
"ज़" = "ஃஜ"
"ड़" = "ஃட²"
"ढ़" = "ஃட³"
"फ़" = "ஃப"
"य़" = "ஃய"
"ऱ" = "ற"
"ऴ" = "ழ"
"ऩ" = "ன"
