[vowels]
"अ" = "அ"
"आ" = "ஆ"
"इ" = "இ"
"ई" = "ஈ"
"उ" = "உ"
"ऊ" = "ஊ"
"ऋ" = "ரு'"
"ॠ" = "ரூ'"
"ऌ" = "லு'"
"ॡ" = "லூ'"
"ऎ" = "எ"
"ए" = "ஏ"
"ऐ" = "ஐ"
"ऒ" = "ஒ"
"ओ" = "ஓ"
"औ" = "ஔ"

[vowel_marks]
"ा" = "ா"
"ि" = "ி"
"ी" = "ீ"
"ु" = "ு"
"ू" = "ூ"
"ृ" = "்ரு'"
"ॄ" = "்ரூ'"
"ॢ" = "்லு'"
"ॣ" = "்லூ'"
"ॆ" = "ெ"
"े" = "ே"
"ै" = "ை"
"ॊ" = "ொ"
"ो" = "ோ"
"ौ" = "ௌ"

[yogavaahas]
"ं" = "ஂ"
"ः" = "ஃ"
"ँ" = ""

[virama]
"्" = "்"

[consonants]
"क" = "க"
"ख" = "க"
"ग" = "க"
"घ" = "க"
"ङ" = "ங"
"च" = "ச"
"छ" = "ச"
"ज" = "ஜ"
"झ" = "ச"
"ञ" = "ஞ"
"ट" = "ட"
"ठ" = "ட"
"ड" = "ட"
"ढ" = "ட"
"ण" = "ண"
"त" = "த"
"थ" = "த"
"द" = "த"
"ध" = "த"
"न" = "ந"
"प" = "ப"
"फ" = "ப"
"ब" = "ப"
"भ" = "ப"
"म" = "ம"
"य" = "ய"
"र" = "ர"
"ल" = "ல"
"व" = "வ"
"श" = "ஶ"
"ष" = "ஷ"
"स" = "ஸ"
"ह" = "ஹ"
"ळ" = "ள"
"क्ष" = "க்ஷ"
"ज्ञ" = "ஜ்ஞ"

[symbols]
"०" = "௦"
"१" = "௧"
"२" = "௨"
"३" = "௩"
"४" = "௪"
"५" = "௫"
"६" = "௬"
"७" = "௭"
"८" = "௮"
"९" = "௯"
"ॐ" = "ௐ"
"ऽ" = "ऽ"
"।" = "।"
"॥" = "॥"

[extra_consonants]
"क़" = "ஃ'க"
"ख़" = "ஃக²"
"ग़" = "ஃக³"
"ज़" = "ஃஜ"
"ड़" = "ஃட²"
"ढ़" = "ஃட³"
"फ़" = "ஃப"
"य़" = "ஃய"
"ऱ" = "ற"
"ऴ" = "ழ"
"ऩ" = "ன"
