vowels = [ "роЕ", "роЖ", "роЗ", "роИ", "роЙ", "роК", "ЁСМЛ", "ЁСНа", "ЁСММ", "ЁСНб", "роО", "роП", "роР", "роТ", "роУ", "роФ",]
vowel_marks = [ "ро╛", "ро┐", "рпА", "рпБ", "рпВ", "ЁСНГ", "ЁСНД", "ЁСНв", "ЁСНг", "рпЖ", "рпЗ", "рпИ", "рпК", "рпЛ", "рпМ",]
yogavaahas = [ "ЁСМВ", "ЁСМГ", "ЁСМБ",]
virama = [ "рпН",]
consonants = [ "роХ", "ЁСМЦ", "ЁСМЧ", "ЁСМШ", "роЩ", "роЪ", "ЁСМЫ", "роЬ", "ЁСМЭ", "роЮ", "роЯ", "ЁСМа", "ЁСМб", "ЁСМв", "рог", "род", "ЁСМе", "ЁСМж", "ЁСМз", "рои", "рок", "ЁСМл", "ЁСМм", "ЁСМн", "роо", "роп", "ро░", "ро▓", "ро╡", "ро╢", "ро╖", "ро╕", "ро╣", "ро│", "роХрпНро╖", "роЬрпНроЮ",]
symbols = [ "рпж", "рпз", "рпи", "рпй", "рпк", "рпл", "рпм", "рпн", "рпо", "рпп", "рпР", "ЁСМ╜", "ред", "рее",]
candra = [ "рпЖ",]
extra_consonants = [ "роХЁСМ╝", "ЁСМЦЁСМ╝", "ЁСМЧЁСМ╝", "роЬЁСМ╝", "ЁСМбЁСМ╝", "ЁСМвЁСМ╝", "ЁСМлЁСМ╝", "ропЁСМ╝", "ро▒", "ро┤", "рой",]
