[vowels]
"рдЕ" = "роЕ"
"рдЖ" = "роЖ"
"рдЗ" = "роЗ"
"рдИ" = "роИ"
"рдЙ" = "роЙ"
"рдК" = "роК"
"рдЛ" = "ЁСМЛ"
"реа" = "ЁСНа"
"рдМ" = "ЁСММ"
"реб" = "ЁСНб"
"рдО" = "роО"
"рдП" = "роП"
"рдР" = "роР"
"рдТ" = "роТ"
"рдУ" = "роУ"
"рдФ" = "роФ"

[vowel_marks]
"рд╛" = "ро╛"
"рд┐" = "ро┐"
"реА" = "рпА"
"реБ" = "рпБ"
"реВ" = "рпВ"
"реГ" = "ЁСНГ"
"реД" = "ЁСНД"
"рев" = "ЁСНв"
"рег" = "ЁСНг"
"реЖ" = "рпЖ"
"реЗ" = "рпЗ"
"реИ" = "рпИ"
"реК" = "рпК"
"реЛ" = "рпЛ"
"реМ" = "рпМ"

[yogavaahas]
"рдВ" = "ЁСМВ"
"рдГ" = "ЁСМГ"
"рдБ" = "ЁСМБ"

[virama]
"реН" = "рпН"

[consonants]
"рдХ" = "роХ"
"рдЦ" = "ЁСМЦ"
"рдЧ" = "ЁСМЧ"
"рдШ" = "ЁСМШ"
"рдЩ" = "роЩ"
"рдЪ" = "роЪ"
"рдЫ" = "ЁСМЫ"
"рдЬ" = "роЬ"
"рдЭ" = "ЁСМЭ"
"рдЮ" = "роЮ"
"рдЯ" = "роЯ"
"рда" = "ЁСМа"
"рдб" = "ЁСМб"
"рдв" = "ЁСМв"
"рдг" = "рог"
"рдд" = "род"
"рде" = "ЁСМе"
"рдж" = "ЁСМж"
"рдз" = "ЁСМз"
"рди" = "рои"
"рдк" = "рок"
"рдл" = "ЁСМл"
"рдм" = "ЁСМм"
"рдн" = "ЁСМн"
"рдо" = "роо"
"рдп" = "роп"
"рд░" = "ро░"
"рд▓" = "ро▓"
"рд╡" = "ро╡"
"рд╢" = "ро╢"
"рд╖" = "ро╖"
"рд╕" = "ро╕"
"рд╣" = "ро╣"
"рд│" = "ро│"
"рдХреНрд╖" = "роХрпНро╖"
"рдЬреНрдЮ" = "роЬрпНроЮ"

[symbols]
"реж" = "рпж"
"рез" = "рпз"
"реи" = "рпи"
"рей" = "рпй"
"рек" = "рпк"
"рел" = "рпл"
"рем" = "рпм"
"рен" = "рпн"
"рео" = "рпо"
"реп" = "рпп"
"реР" = "рпР"
"рд╜" = "ЁСМ╜"
"ред" = "ред"
"рее" = "рее"

[candra]
"реЕ" = "рпЖ"

[extra_consonants]
"реШ" = "роХЁСМ╝"
"реЩ" = "ЁСМЦЁСМ╝"
"реЪ" = "ЁСМЧЁСМ╝"
"реЫ" = "роЬЁСМ╝"
"реЬ" = "ЁСМбЁСМ╝"
"рдврд╝" = "ЁСМвЁСМ╝"
"реЮ" = "ЁСМлЁСМ╝"
"реЯ" = "ропЁСМ╝"
"рд▒" = "ро▒"
"рд┤" = "ро┤"
"рдй" = "рой"
