vowels = [ "அ", "ஆ", "இ", "ஈ", "உ", "ஊ", "ரு'", "ரூ'", "லு'", "லூ'", "எ", "ஏ", "ஐ", "ஒ", "ஓ", "ஔ",]
vowel_marks = [ "ா", "ி", "ீ", "ு", "ூ", "்ரு'", "்ரூ'", "்லு'", "்லூ'", "ெ", "ே", "ை", "ொ", "ோ", "ௌ",]
yogavaahas = [ "ஂ", "ஃ", "",]
virama = [ "்",]
consonants = [ "க", "க", "க", "க", "ங", "ச", "ச", "ஜ", "ச", "ஞ", "ட", "ட", "ட", "ட", "ண", "த", "த", "த", "த", "ந", "ப", "ப", "ப", "ப", "ம", "ய", "ர", "ல", "வ", "ஶ", "ஷ", "ஸ", "ஹ", "ள", "க்ஷ", "ஜ்ஞ",]
symbols = [ "௦", "௧", "௨", "௩", "௪", "௫", "௬", "௭", "௮", "௯", "ௐ", "ऽ", "।", "॥",]
extra_consonants = [ "ஃ'க", "ஃக²", "ஃக³", "ஃஜ", "ஃட²", "ஃட³", "ஃப", "ஃய", "ற", "ழ", "ன",]
