[vowels]
"अ" = "అ"
"आ" = "ఆ"
"इ" = "ఇ"
"ई" = "ఈ"
"उ" = "ఉ"
"ऊ" = "ఊ"
"ऋ" = "ఋ"
"ॠ" = "ౠ"
"ऌ" = "ఌ"
"ॡ" = "ౡ"
"ऎ" = "ఎ"
"ए" = "ఏ"
"ऐ" = "ఐ"
"ऒ" = "ఒ"
"ओ" = "ఓ"
"औ" = "ఔ"

[vowel_marks]
"ा" = "ా"
"ि" = "ి"
"ी" = "ీ"
"ु" = "ు"
"ू" = "ూ"
"ृ" = "ృ"
"ॄ" = "ౄ"
"ॢ" = "ౢ"
"ॣ" = "ౣ"
"ॆ" = "ె"
"े" = "ే"
"ै" = "ై"
"ॊ" = "ొ"
"ो" = "ో"
"ौ" = "ౌ"

[yogavaahas]
"ं" = "ం"
"ः" = "ః"
"ँ" = "ఁ"

[virama]
"्" = "్"

[consonants]
"क" = "క"
"ख" = "ఖ"
"ग" = "గ"
"घ" = "ఘ"
"ङ" = "ఙ"
"च" = "చ"
"छ" = "ఛ"
"ज" = "జ"
"झ" = "ఝ"
"ञ" = "ఞ"
"ट" = "ట"
"ठ" = "ఠ"
"ड" = "డ"
"ढ" = "ఢ"
"ण" = "ణ"
"त" = "త"
"थ" = "థ"
"द" = "ద"
"ध" = "ధ"
"न" = "న"
"प" = "ప"
"फ" = "ఫ"
"ब" = "బ"
"भ" = "భ"
"म" = "మ"
"य" = "య"
"र" = "ర"
"ल" = "ల"
"व" = "వ"
"श" = "శ"
"ष" = "ష"
"स" = "స"
"ह" = "హ"
"ळ" = "ళ"
"क्ष" = "క్ష"
"ज्ञ" = "జ్ఞ"

[symbols]
"०" = "౦"
"१" = "౧"
"२" = "౨"
"३" = "౩"
"४" = "౪"
"५" = "౫"
"६" = "౬"
"७" = "౭"
"८" = "౮"
"९" = "౯"
"ॐ" = "ఓం"
"ऽ" = "ఽ"
"।" = "।"
"॥" = "॥"

[extra_consonants]
"क़" = ""
"ख़" = ""
"ग़" = ""
"ज़" = ""
"ड़" = ""
"ढ़" = ""
"फ़" = ""
"य़" = ""
"ऱ" = "ఱ"
"ऴ" = "ఴ"
