[vowels]
"अ" = "อ"
"आ" = "อา"
"इ" = "อิ"
"ई" = "อี"
"उ" = "อุ"
"ऊ" = "อู"
"ऋ" = "ฤ"
"ॠ" = "ฤๅ"
"ऌ" = "ฦ"
"ॡ" = "ฦๅ"
"ऎ" = "เอะ"
"ए" = "เอ"
"ऐ" = "ไอ"
"ऒ" = "โอะ"
"ओ" = "โอ"
"औ" = "เอา"

[vowel_marks]
"ा" = "า"
"ि" = "ิ"
"ी" = "ี"
"ु" = "ุ"
"ू" = "ู"
"ृ" = "ฺฤ"
"ॄ" = "ฺฤๅ"
"ॢ" = "ฺฦ"
"ॣ" = "ฺฦๅ"
"ॆ" = "เะ"
"े" = "เ"
"ै" = "ไ"
"ॊ" = "โะ"
"ो" = "โ"
"ौ" = "เา"

[yogavaahas]
"ं" = "ํ"
"ः" = "ห์"
"ँ" = "ํ"

[virama]
"्" = "ฺ"

[consonants]
"क" = "ก"
"ख" = "ข"
"ग" = "ค"
"घ" = "ฆ"
"ङ" = "ง"
"च" = "จ"
"छ" = "ฉ"
"ज" = "ช"
"झ" = "ฌ"
"ञ" = "ญ"
"ट" = "ฏ"
"ठ" = "ฐ"
"ड" = "ฑ"
"ढ" = "ฒ"
"ण" = "ณ"
"त" = "ต"
"थ" = "ถ"
"द" = "ท"
"ध" = "ธ"
"न" = "น"
"प" = "ป"
"फ" = "ผ"
"ब" = "พ"
"भ" = "ภ"
"म" = "ม"
"य" = "ย"
"र" = "ร"
"ल" = "ล"
"व" = "ว"
"श" = "ศ"
"ष" = "ษ"
"स" = "ส"
"ह" = "ห"
"ळ" = "ฬ"
"क्ष" = "กฺษ"
"ज्ञ" = "ชฺญ"

[symbols]
"०" = "๐"
"१" = "๑"
"२" = "๒"
"३" = "๓"
"४" = "๔"
"५" = "๕"
"६" = "๖"
"७" = "๗"
"८" = "๘"
"९" = "๙"
"ॐ" = "โอํ"
"ऽ" = "'"
"।" = "ฯ"
"॥" = "๚"

[candra]
"ॅ" = "แะ"

[extra_consonants]
"क़" = "ก"
"ख़" = "ข"
"ग़" = "ค"
"ज़" = "ซ"
"ड़" = "ร"
"ढ़" = "รฺห"
"फ़" = "ฟ"
"य़" = "ย"
"ऱ" = "ร"
