vowels = [ "อ", "อา", "อิ", "อี", "อุ", "อู", "ฤ", "ฤๅ", "ฦ", "ฦๅ", "เอะ", "เอ", "ไอ", "โอะ", "โอ", "เอา",]
vowel_marks = [ "า", "ิ", "ี", "ุ", "ู", "ฺฤ", "ฺฤๅ", "ฺฦ", "ฺฦๅ", "เะ", "เ", "ไ", "โะ", "โ", "เา",]
yogavaahas = [ "ํ", "ห์", "ํ",]
virama = [ "ฺ",]
consonants = [ "ก", "ข", "ค", "ฆ", "ง", "จ", "ฉ", "ช", "ฌ", "ญ", "ฏ", "ฐ", "ฑ", "ฒ", "ณ", "ต", "ถ", "ท", "ธ", "น", "ป", "ผ", "พ", "ภ", "ม", "ย", "ร", "ล", "ว", "ศ", "ษ", "ส", "ห", "ฬ", "กฺษ", "ชฺญ",]
symbols = [ "๐", "๑", "๒", "๓", "๔", "๕", "๖", "๗", "๘", "๙", "โอํ", "'", "ฯ", "๚",]
candra = [ "แะ",]
extra_consonants = [ "ก", "ข", "ค", "ซ", "ร", "รฺห", "ฟ", "ย", "ร",]
