vowels = [ "ཨ", "ཨཱ", "ཨི", "ཨཱི", "ཨུ", "ཨཱུ", "རྀ", "རཱྀ", "ལྀ", "ལཱྀ", "ཨེ", "ཨེ", "ཨཻ", "ཨོ", "ཨོ", "ཨཽ",]
vowel_marks = [ "ཱ", "ི", "ཱི", "ུ", "ཱུ", "ྲྀ", "ྲཱྀ", "ླྀ", "ླཱྀ", "ེ", "ེ", "ཻ", "ོ", "ོ", "ཽ",]
yogavaahas = [ "ཾ", "ཿ", "ྃ",]
virama = [ "",]
consonants = [ "ཀ", "ཁ", "ག", "གྷ", "ང", "ཙ", "ཚ", "ཛ", "ཛྷ", "ཉ", "ཊ", "ཋ", "ཌ", "ཌྷ", "ཎ", "ཏ", "ཐ", "ད", "དྷ", "ན", "པ", "ཕ", "བ", "བྷ", "མ", "ཡ", "ར", "ལ", "བ", "ཤ", "ཥ", "ས", "ཧ", "ལ༹", "ཀྵ", "ཛྙ",]
symbols = [ "༠", "༡", "༢", "༣", "༤", "༥", "༦", "༧", "༨", "༩", "ༀ", "྅", "།", "༎",]
candra = [ "ེ",]
extra_consonants = [ "ཀ༹", "ཁ༹", "ག༹", "ཟ", "ཌ༹", "ཌྷ༹", "ཕ༹", "ཡ༹", "ར༹",]
