[vowels]
"अ" = "ཨ"
"आ" = "ཨཱ"
"इ" = "ཨི"
"ई" = "ཨཱི"
"उ" = "ཨུ"
"ऊ" = "ཨཱུ"
"ऋ" = "རྀ"
"ॠ" = "རཱྀ"
"ऌ" = "ལྀ"
"ॡ" = "ལཱྀ"
"ऎ" = "ཨེ"
"ए" = "ཨེ"
"ऐ" = "ཨཻ"
"ऒ" = "ཨོ"
"ओ" = "ཨོ"
"औ" = "ཨཽ"

[vowel_marks]
"ा" = "ཱ"
"ि" = "ི"
"ी" = "ཱི"
"ु" = "ུ"
"ू" = "ཱུ"
"ृ" = "ྲྀ"
"ॄ" = "ྲཱྀ"
"ॢ" = "ླྀ"
"ॣ" = "ླཱྀ"
"ॆ" = "ེ"
"े" = "ེ"
"ै" = "ཻ"
"ॊ" = "ོ"
"ो" = "ོ"
"ौ" = "ཽ"

[yogavaahas]
"ं" = "ཾ"
"ः" = "ཿ"
"ँ" = "ྃ"

[virama]
"्" = ""

[consonants]
"क" = "ཀ"
"ख" = "ཁ"
"ग" = "ག"
"घ" = "གྷ"
"ङ" = "ང"
"च" = "ཙ"
"छ" = "ཚ"
"ज" = "ཛ"
"झ" = "ཛྷ"
"ञ" = "ཉ"
"ट" = "ཊ"
"ठ" = "ཋ"
"ड" = "ཌ"
"ढ" = "ཌྷ"
"ण" = "ཎ"
"त" = "ཏ"
"थ" = "ཐ"
"द" = "ད"
"ध" = "དྷ"
"न" = "ན"
"प" = "པ"
"फ" = "ཕ"
"ब" = "བ"
"भ" = "བྷ"
"म" = "མ"
"य" = "ཡ"
"र" = "ར"
"ल" = "ལ"
"व" = "བ"
"श" = "ཤ"
"ष" = "ཥ"
"स" = "ས"
"ह" = "ཧ"
"ळ" = "ལ༹"
"क्ष" = "ཀྵ"
"ज्ञ" = "ཛྙ"

[symbols]
"०" = "༠"
"१" = "༡"
"२" = "༢"
"३" = "༣"
"४" = "༤"
"५" = "༥"
"६" = "༦"
"७" = "༧"
"८" = "༨"
"९" = "༩"
"ॐ" = "ༀ"
"ऽ" = "྅"
"।" = "།"
"॥" = "༎"

[candra]
"ॅ" = "ེ"

[extra_consonants]
"क़" = "ཀ༹"
"ख़" = "ཁ༹"
"ग़" = "ག༹"
"ज़" = "ཟ"
"ड़" = "ཌ༹"
"ढ़" = "ཌྷ༹"
"फ़" = "ཕ༹"
"य़" = "ཡ༹"
"ऱ" = "ར༹"
