vowels = [ "اَ", "آ", "اِ", "اِی", "اُ", "اُو", "رِ", "رِی", "لِ", "لِی", "اے", "اے", "اَے", "او", "او", "اَو",]
vowel_marks = [ "ا", "ِ", "ِی", "ُ", "ُو", "ْرِ", "ْرِی", "ْلِ", "ْلِی", "ے", "ے", "ے", "و", "و", "و",]
yogavaahas = [ "ں", "ہ", "ں",]
virama = [ "ْ",]
consonants = [ "کَ", "کھَ", "گَ", "گھَ", "نَ", "چَ", "چھَ", "جَ", "جھَ", "نَ", "ٹَ", "ٹھَ", "ڈَ", "ڈھَ", "نَ", "تَ", "تھَ", "دَ", "دھَ", "نَ", "پَ", "پھَ", "بَ", "بھَ", "مَ", "یَ", "رَ", "لَ", "وَ", "شَ", "شَ", "سَ", "ہَ", "لَ", "کْشَ", "جْنَ",]
symbols = [ "۰", "۱", "۲", "۳", "۴", "۵", "۶", "۷", "۸", "۹", "اومْ", "", "۔", "۔۔",]
candra = [ "ے",]
extra_consonants = [ "قَ", "خَ", "غَ", "زَ", "ڑَ", "ڑھَ", "فَ", "یَ", "رَ",]
