[vowels]
"अ" = "اَ"
"आ" = "آ"
"इ" = "اِ"
"ई" = "اِی"
"उ" = "اُ"
"ऊ" = "اُو"
"ऋ" = "رِ"
"ॠ" = "رِی"
"ऌ" = "لِ"
"ॡ" = "لِی"
"ऎ" = "اے"
"ए" = "اے"
"ऐ" = "اَے"
"ऒ" = "او"
"ओ" = "او"
"औ" = "اَو"

[vowel_marks]
"ा" = "ا"
"ि" = "ِ"
"ी" = "ِی"
"ु" = "ُ"
"ू" = "ُو"
"ृ" = "ْرِ"
"ॄ" = "ْرِی"
"ॢ" = "ْلِ"
"ॣ" = "ْلِی"
"ॆ" = "ے"
"े" = "ے"
"ै" = "ے"
"ॊ" = "و"
"ो" = "و"
"ौ" = "و"

[yogavaahas]
"ं" = "ں"
"ः" = "ہ"
"ँ" = "ں"

[virama]
"्" = "ْ"

[consonants]
"क" = "کَ"
"ख" = "کھَ"
"ग" = "گَ"
"घ" = "گھَ"
"ङ" = "نَ"
"च" = "چَ"
"छ" = "چھَ"
"ज" = "جَ"
"झ" = "جھَ"
"ञ" = "نَ"
"ट" = "ٹَ"
"ठ" = "ٹھَ"
"ड" = "ڈَ"
"ढ" = "ڈھَ"
"ण" = "نَ"
"त" = "تَ"
"थ" = "تھَ"
"द" = "دَ"
"ध" = "دھَ"
"न" = "نَ"
"प" = "پَ"
"फ" = "پھَ"
"ब" = "بَ"
"भ" = "بھَ"
"म" = "مَ"
"य" = "یَ"
"र" = "رَ"
"ल" = "لَ"
"व" = "وَ"
"श" = "شَ"
"ष" = "شَ"
"स" = "سَ"
"ह" = "ہَ"
"ळ" = "لَ"
"क्ष" = "کْشَ"
"ज्ञ" = "جْنَ"

[symbols]
"०" = "۰"
"१" = "۱"
"२" = "۲"
"३" = "۳"
"४" = "۴"
"५" = "۵"
"६" = "۶"
"७" = "۷"
"८" = "۸"
"९" = "۹"
"ॐ" = "اومْ"
"ऽ" = ""
"।" = "۔"
"॥" = "۔۔"

[candra]
"ॅ" = "ے"

[extra_consonants]
"क़" = "قَ"
"ख़" = "خَ"
"ग़" = "غَ"
"ज़" = "زَ"
"ड़" = "ڑَ"
"ढ़" = "ڑھَ"
"फ़" = "فَ"
"य़" = "یَ"
"ऱ" = "رَ"
