[vowels]
"अ" = "அ"
"आ" = "ஆ"
"इ" = "இ"
"ई" = "ஈ"
"उ" = "உ"
"ऊ" = "ஊ"
"ऋ" = "ரு"
"ॠ" = "ரூ"
"ऌ" = "லு"
"ॡ" = "லூ"
"ऎ" = "எ"
"ए" = "ஏ"
"ऐ" = "ஐ"
"ऒ" = "ஒ"
"ओ" = "ஓ"
"औ" = "ஔ"

[vowel_marks]
"ा" = "ா"
"ि" = "ி"
"ी" = "ீ"
"ु" = "ு"
"ू" = "ூ"
"ृ" = "்ரு"
"ॄ" = "்ரூ"
"ॢ" = "்லு"
"ॣ" = "்லூ"
"ॆ" = "ெ"
"े" = "ே"
"ै" = "ை"
"ॊ" = "ொ"
"ो" = "ோ"
"ौ" = "ௌ"

[yogavaahas]
"ं" = "ம்"
"ः" = "꞉"
"ँ" = "ம்"

[virama]
"्" = "்"

[consonants]
"क" = "க"
"ख" = "க"
"ग" = "க"
"घ" = "க"
"ङ" = "ங"
"च" = "ச"
"छ" = "ச"
"ज" = "ச"
"झ" = "ச"
"ञ" = "ஞ"
"ट" = "ட"
"ठ" = "ட"
"ड" = "ட"
"ढ" = "ட"
"ण" = "ண"
"त" = "த"
"थ" = "த"
"द" = "த"
"ध" = "த"
"न" = "ந"
"प" = "ப"
"फ" = "ப"
"ब" = "ப"
"भ" = "ப"
"म" = "ம"
"य" = "ய"
"र" = "ர"
"ल" = "ல"
"व" = "வ"
"श" = "ச"
"ष" = "ச"
"स" = "ச"
"ह" = "க"
"ळ" = "ள"
"क्ष" = "க்ச"
"ज्ञ" = "ச்ஞ"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "ஓம்"
"ऽ" = ""
"।" = "."
"॥" = ".."

[candra]
"ॅ" = "ெ"

[extra_consonants]
"क़" = "க"
"ख़" = "க"
"ग़" = "க"
"ज़" = "ச"
"ड़" = "ட"
"ढ़" = "ட"
"फ़" = "ப"
"य़" = "ய"
"ऱ" = "ற"
