vowels = [ "𞋁", "𞋀", "𞋜", "𞋜", "𞋞", "𞋞", "𞋗𞋞", "𞋗𞋞", "𞋈𞋞", "𞋈𞋞", "𞋛", "𞋛", "𞋀𞋜", "𞋕", "𞋕", "𞋖",]
vowel_marks = [ "𞋀", "𞋜", "𞋜", "𞋞", "𞋞", "𞋗𞋞", "𞋗𞋞", "𞋈𞋞", "𞋈𞋞", "𞋛", "𞋛", "𞋀𞋜", "𞋕", "𞋕", "𞋖",]
yogavaahas = [ "𞋝", "𞋫", "𞋉",]
virama = [ "",]
consonants = [ "𞋔𞋁", "𞋙𞋁", "𞋅𞋁", "𞋅𞋁", "𞋝𞋁", "𞋃𞋁", "𞋃𞋁", "𞋐𞋁", "𞋐𞋁", "𞋩𞋁", "𞋋𞋁", "𞋌𞋁", "𞋄𞋁", "𞋄𞋁", "𞋉𞋁", "𞋋𞋁", "𞋌𞋁", "𞋄𞋁", "𞋄𞋁", "𞋉𞋁", "𞋊𞋁", "𞋇𞋁", "𞋂𞋁", "𞋂𞋁", "𞋘𞋁", "𞋆𞋁", "𞋗𞋁", "𞋈𞋁", "𞋓𞋁", "𞋏𞋁", "𞋏𞋁", "𞋎𞋁", "𞋚𞋁", "𞋟𞋁", "𞋔𞋏𞋁", "𞋐𞋩𞋁",]
symbols = [ "𞋰", "𞋱", "𞋲", "𞋳", "𞋴", "𞋵", "𞋶", "𞋷", "𞋸", "𞋹", "𞋦", "", ".", "..",]
candra = [ "𞋛",]
extra_consonants = [ "𞋔𞋁", "𞋙𞋁", "𞋅𞋁", "𞋑𞋁", "𞋄𞋁", "𞋄𞋁", "𞋍𞋁", "𞋆𞋁", "𞋗𞋁",]
