[vowels]
"рдЕ" = "ЁЮЛБ"
"рдЖ" = "ЁЮЛА"
"рдЗ" = "ЁЮЛЬ"
"рдИ" = "ЁЮЛЬ"
"рдЙ" = "ЁЮЛЮ"
"рдК" = "ЁЮЛЮ"
"рдЛ" = "ЁЮЛЧЁЮЛЮ"
"реа" = "ЁЮЛЧЁЮЛЮ"
"рдМ" = "ЁЮЛИЁЮЛЮ"
"реб" = "ЁЮЛИЁЮЛЮ"
"рдО" = "ЁЮЛЫ"
"рдП" = "ЁЮЛЫ"
"рдР" = "ЁЮЛАЁЮЛЬ"
"рдТ" = "ЁЮЛХ"
"рдУ" = "ЁЮЛХ"
"рдФ" = "ЁЮЛЦ"

[vowel_marks]
"рд╛" = "ЁЮЛА"
"рд┐" = "ЁЮЛЬ"
"реА" = "ЁЮЛЬ"
"реБ" = "ЁЮЛЮ"
"реВ" = "ЁЮЛЮ"
"реГ" = "ЁЮЛЧЁЮЛЮ"
"реД" = "ЁЮЛЧЁЮЛЮ"
"рев" = "ЁЮЛИЁЮЛЮ"
"рег" = "ЁЮЛИЁЮЛЮ"
"реЖ" = "ЁЮЛЫ"
"реЗ" = "ЁЮЛЫ"
"реИ" = "ЁЮЛАЁЮЛЬ"
"реК" = "ЁЮЛХ"
"реЛ" = "ЁЮЛХ"
"реМ" = "ЁЮЛЦ"

[yogavaahas]
"рдВ" = "ЁЮЛЭ"
"рдГ" = "ЁЮЛл"
"рдБ" = "ЁЮЛЙ"

[virama]
"реН" = ""

[consonants]
"рдХ" = "ЁЮЛФЁЮЛБ"
"рдЦ" = "ЁЮЛЩЁЮЛБ"
"рдЧ" = "ЁЮЛЕЁЮЛБ"
"рдШ" = "ЁЮЛЕЁЮЛБ"
"рдЩ" = "ЁЮЛЭЁЮЛБ"
"рдЪ" = "ЁЮЛГЁЮЛБ"
"рдЫ" = "ЁЮЛГЁЮЛБ"
"рдЬ" = "ЁЮЛРЁЮЛБ"
"рдЭ" = "ЁЮЛРЁЮЛБ"
"рдЮ" = "ЁЮЛйЁЮЛБ"
"рдЯ" = "ЁЮЛЛЁЮЛБ"
"рда" = "ЁЮЛМЁЮЛБ"
"рдб" = "ЁЮЛДЁЮЛБ"
"рдв" = "ЁЮЛДЁЮЛБ"
"рдг" = "ЁЮЛЙЁЮЛБ"
"рдд" = "ЁЮЛЛЁЮЛБ"
"рде" = "ЁЮЛМЁЮЛБ"
"рдж" = "ЁЮЛДЁЮЛБ"
"рдз" = "ЁЮЛДЁЮЛБ"
"рди" = "ЁЮЛЙЁЮЛБ"
"рдк" = "ЁЮЛКЁЮЛБ"
"рдл" = "ЁЮЛЗЁЮЛБ"
"рдм" = "ЁЮЛВЁЮЛБ"
"рдн" = "ЁЮЛВЁЮЛБ"
"рдо" = "ЁЮЛШЁЮЛБ"
"рдп" = "ЁЮЛЖЁЮЛБ"
"рд░" = "ЁЮЛЧЁЮЛБ"
"рд▓" = "ЁЮЛИЁЮЛБ"
"рд╡" = "ЁЮЛУЁЮЛБ"
"рд╢" = "ЁЮЛПЁЮЛБ"
"рд╖" = "ЁЮЛПЁЮЛБ"
"рд╕" = "ЁЮЛОЁЮЛБ"
"рд╣" = "ЁЮЛЪЁЮЛБ"
"рд│" = "ЁЮЛЯЁЮЛБ"
"рдХреНрд╖" = "ЁЮЛФЁЮЛПЁЮЛБ"
"рдЬреНрдЮ" = "ЁЮЛРЁЮЛйЁЮЛБ"

[symbols]
"реж" = "ЁЮЛ░"
"рез" = "ЁЮЛ▒"
"реи" = "ЁЮЛ▓"
"рей" = "ЁЮЛ│"
"рек" = "ЁЮЛ┤"
"рел" = "ЁЮЛ╡"
"рем" = "ЁЮЛ╢"
"рен" = "ЁЮЛ╖"
"рео" = "ЁЮЛ╕"
"реп" = "ЁЮЛ╣"
"реР" = "ЁЮЛж"
"рд╜" = ""
"ред" = "."
"рее" = ".."

[candra]
"реЕ" = "ЁЮЛЫ"

[extra_consonants]
"реШ" = "ЁЮЛФЁЮЛБ"
"реЩ" = "ЁЮЛЩЁЮЛБ"
"реЪ" = "ЁЮЛЕЁЮЛБ"
"реЫ" = "ЁЮЛСЁЮЛБ"
"реЬ" = "ЁЮЛДЁЮЛБ"
"рдврд╝" = "ЁЮЛДЁЮЛБ"
"реЮ" = "ЁЮЛНЁЮЛБ"
"реЯ" = "ЁЮЛЖЁЮЛБ"
"рд▒" = "ЁЮЛЧЁЮЛБ"
