_vowel_comment = [ "omissions  from optitrans_dravidian", "ea", "oa",]
_yogavaahas_comment = [ "omissions  from optitrans_dravidian", "kH", "pH",]

[vowels]
"अ" = "a"
"आ" = "A"
"इ" = "i"
"ई" = "I"
"उ" = "u"
"ऊ" = "U"
"ऋ" = "Ru"
"ॠ" = "RU"
"ऌ" = "~lu"
"ॡ" = "~lU"
"ऎ" = "e"
"ए" = "E"
"ऐ" = "ai"
"ऒ" = "o"
"ओ" = "O"
"औ" = "au"
"ऍ" = ""
"ऑ" = ""

[yogavaahas]
"ं" = "M"
"ः" = "H"
"ँ" = "~M"
"ᳵ" = ""
"ᳶ" = ""
"ꣳ" = "(gg)"

[virama]
"्" = ""

[consonants]
"क" = "k"
"ख" = "kh"
"ग" = "g"
"घ" = "gh"
"ङ" = "~g"
"च" = "ch"
"छ" = "Ch"
"ज" = "j"
"झ" = "jh"
"ञ" = "~j"
"ट" = "T"
"ठ" = "Th"
"ड" = "D"
"ढ" = "Dh"
"ण" = "N"
"त" = "t"
"थ" = "th"
"द" = "d"
"ध" = "dh"
"न" = "n"
"प" = "p"
"फ" = "ph"
"ब" = "b"
"भ" = "bh"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = "sh"
"ष" = "Sh"
"स" = "s"
"ह" = "h"
"ळ" = "L"
"क्ष" = "kSh"
"ज्ञ" = "j~ja"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "OM"
"ऽ" = "&"
"।" = "|"
"॥" = "||"

[candra]
"ॅ" = "~M"

[zwj]
"\u200d" = "^"

[zwnj]
"\u200c" = "^^"

[skip]
"" = "_"

[accents]
"॑" = "#"
"॒" = "q"
"᳡" = "Q"
"꣡" = "V"
"꣢" = "W"
"꣣" = "$"

[alternates]
A = [ "aa",]
I = [ "ee",]
U = [ "oo",]
kh = [ "K",]
gh = [ "G",]
ch = [ "c",]
Ch = [ "C",]
jh = [ "J",]
ph = [ "P",]
bh = [ "B",]
"~n" = [ "JN",]
v = [ "w",]
sh = [ "S",]
h = [ "~h",]
V = [ "x",]
"|" = [ ".",]
"||" = [ "..",]
