[vowels]
"अ" = "а"
"आ" = "а̄"
"इ" = "и"
"ई" = "ӣ"
"उ" = "у"
"ऊ" = "ӯ"
"ऋ" = "р̣"
"ॠ" = "р̣̄"
"ऌ" = "л̣"
"ॡ" = "л̣̄"
"ऎ" = "э̆"
"ए" = "э"
"ऐ" = "аи"
"ऒ" = "о̆"
"ओ" = "о"
"औ" = "ау"

[yogavaahas]
"ं" = "м̣"
"ः" = "х̣"
"ँ" = "м̐"

[virama]
"्" = ""

[accents]
"॑" = "̭"
"॒" = "॒"
"᳡" = "̀"
"꣡" = "́"
"꣢" = "²"
"꣣" = "³"
"꣤" = "⁴"
"꣥" = "⁵"
"꣦" = "⁶"
"꣧" = "⁷"
"꣨" = "⁸"
"꣩" = "⁹"
"꣪" = "꣪"
"꣫" = "꣫"
"꣬" = "꣬"
"꣭" = "꣭"
"꣮" = "꣮"
"꣯" = "꣯"
"꣰" = "꣰"
"꣱" = "꣱"

[consonants]
"क" = "к"
"ख" = "кх"
"ग" = "г"
"घ" = "гх"
"ङ" = "н̇"
"च" = "ч"
"छ" = "чх"
"ज" = "дж"
"झ" = "джх"
"ञ" = "н̃"
"ट" = "т̣"
"ठ" = "т̣х"
"ड" = "д̣"
"ढ" = "д̣х"
"ण" = "н̣"
"त" = "т"
"थ" = "тх"
"द" = "д"
"ध" = "дх"
"न" = "н"
"प" = "п"
"फ" = "пх"
"ब" = "б"
"भ" = "бх"
"म" = "м"
"य" = "й"
"र" = "р"
"ल" = "л"
"व" = "в"
"श" = "ш́"
"ष" = "ш"
"स" = "с"
"ह" = "х"
"ळ" = "л̤"
"क्ष" = "кш"
"ज्ञ" = "джн̃"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "ом̣"
"ऽ" = "'"
"।" = "।"
"॥" = "॥"

[candra]
"ॅ" = "ӕ"

[extra_consonants]
"क़" = "ԛ"
"ख़" = "к͟х"
"ग़" = "г̇"
"ज़" = "з"
"ड़" = "р̤"
"ढ़" = "р̤х"
"फ़" = "ф"
"य़" = "й̣"
"ऱ" = "р̱"
