vowels = [ "a", "A", "i", "I", "u", "U", "R", "RR", "lR", "lRR", "è", "e", "ai", "ò", "o", "au",]
yogavaahas = [ "M", "H", "~",]
virama = [ "",]
consonants = [ "k", "kh", "g", "gh", "G", "c", "ch", "j", "jh", "J", "T", "Th", "D", "Dh", "N", "t", "th", "d", "dh", "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "z", "S", "s", "h", "L", "kS", "jJ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "OM", "'", "|", "||",]
extra_consonants = [ "q", "qh", "g2", "z2", "r3", "r3h", "f", "Y", "r2", "zh", "n2",]
