vowels = [ "a", "ā", "i", "ī", "u", "ū", "ṛ", "ṝ", "ḷ", "ḹ", "è", "e", "ai", "ò", "o", "au",]
yogavaahas = [ "ṃ", "ḥ", "~",]
virama = [ "",]
accents = [ "̭", "॒", "̀", "́", "²", "³", "⁴", "⁵", "⁶", "⁷", "⁸", "⁹", "꣪", "꣫", "꣬", "꣭", "꣮", "꣯", "꣰", "꣱",]
consonants = [ "k", "kh", "g", "gh", "ṅ", "c", "ch", "j", "jh", "ñ", "ṭ", "ṭh", "ḍ", "ḍh", "ṇ", "t", "th", "d", "dh", "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "ś", "ṣ", "s", "h", "l̤", "kṣ", "jñ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "oṃ", "'", "|", "||",]
extra_consonants = [ "q", "k͟h", "ġ", "z", "r̤", "r̤h", "f", "ẏ", "ṟ", "ḻ", "ṉ",]

[alternates]
"|" = [ ".", "/",]
"||" = [ "..", "//",]
"'" = [ "`",]
"m̐" = [ "ṁ",]
"ṛ" = [ "r̥",]
"ṝ" = [ "ṝ", "r̥̄", "r̥̄",]
"́" = [ "¹",]

[accented_vowel_alternates]
"á" = [ "á",]
"é" = [ "é",]
"í" = [ "í",]
"ó" = [ "ó",]
"ú" = [ "ú",]
"ṛ́" = [ "ŕ̥",]
"à" = [ "à",]
"è" = [ "è",]
"ì" = [ "ì",]
"ò" = [ "ò",]
"ù" = [ "ù",]
"ṛ̀" = [ "r̥̀",]
