vowels = [ "a", "ā", "i", "ī", "u", "ū", "r̥", "r̥̄", "l̥", "l̥̄", "e", "ē", "ai", "o", "ō", "au",]
yogavaahas = [ "ṁ", "ḥ", "~",]
virama = [ "",]
accents = [ "̭", "॒", "̀", "́", "²", "³", "⁴", "⁵", "⁶", "⁷", "⁸", "⁹", "꣪", "꣫", "꣬", "꣭", "꣮", "꣯", "꣰", "꣱",]
consonants = [ "k", "kh", "g", "gh", "ṅ", "c", "ch", "j", "jh", "ñ", "ṭ", "ṭh", "ḍ", "ḍh", "ṇ", "t", "th", "d", "dh", "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "ś", "ṣ", "s", "h", "ḷ", "kṣ", "jñ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ōṁ", "'", "।", "॥",]
extra_consonants = [ "q", "k͟h", "ġ", "z", "ṛ", "ṛh", "f", "ẏ", "ṟ", "ḻ", "ṉ",]

[accented_vowel_alternates]
"á" = [ "á",]
"é" = [ "é",]
"í" = [ "í",]
"ó" = [ "ó",]
"ú" = [ "ú",]
"ŕ̥" = [ "ŕ̥",]
"à" = [ "à",]
"è" = [ "è",]
"ì" = [ "ì",]
"ò" = [ "ò",]
"ù" = [ "ù",]
"r̥̀" = [ "r̥̀",]

[alternates]
"|" = [ ".", "/",]
"||" = [ "..", "//",]
"'" = [ "`",]
"m̐" = [ "ṁ",]
"ṝ" = [ "ṝ", "r̥̄", "r̥̄",]
"́" = [ "¹",]
