vowels = [ "a", "A", "i", "I", "u", "U", "RRi", "RRI", "LLi", "LLI", "è", "e", "ai", "ò", "o", "au",]
yogavaahas = [ "M", "H", ".N",]
virama = [ "",]
consonants = [ "k", "kh", "g", "gh", "~N", "ch", "Ch", "j", "jh", "~n", "T", "Th", "D", "Dh", "N", "t", "th", "d", "dh", "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "sh", "Sh", "s", "h", "L", "kSh", "j~n",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "OM", ".a", "|", "||",]
candra = [ ".c",]
zwj = [ "{}",]
skip = [ "_",]
accents = [ "\\'", "\\_",]
extra_consonants = [ "q", "K", "G", "z", ".D", ".Dh", "f", "Y", "R", "zh",]

[alternates]
A = [ "aa",]
I = [ "ii", "ee",]
U = [ "uu", "oo",]
RRi = [ "R^i",]
RRI = [ "R^I",]
LLi = [ "L^i",]
LLI = [ "L^I",]
M = [ ".m", ".n",]
"~N" = [ "N^",]
ch = [ "c",]
Ch = [ "C", "chh",]
"~n" = [ "JN",]
v = [ "w",]
Sh = [ "S", "shh",]
kSh = [ "kS", "x",]
"j~n" = [ "GY", "dny",]
OM = [ "AUM",]
"\\_" = [ "\\`",]
"\\_H" = [ "\\`H",]
"\\'M" = [ "\\'.m", "\\'.n",]
"\\_M" = [ "\\_.m", "\\_.n", "\\`M", "\\`.m", "\\`.n",]
".a" = [ "~",]
"|" = [ ".",]
"||" = [ "..",]
z = [ "J",]
