vowels = [ "a", "A", "i", "I", "u", "U", "R", "RR", "LLi", "LLI", "e", "E", "ai", "o", "O", "au", "ea", "oa",]
yogavaahas = [ "M", "H", ".N", "kH", "pH",]
virama = [ "",]
consonants = [ "k", "kh", "g", "gh", "~N", "ch", "Ch", "j", "jh", "~n", "T", "Th", "D", "Dh", "N", "t", "th", "d", "dh", "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "sh", "Sh", "s", "h", "L", "x", "jn",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "OM", ".a", "|", "||",]
candra = [ ".c",]
zwj = [ "{}",]
skip = [ "_",]
accents = [ "\\'", "\\_",]
extra_consonants = [ ".k", "q", ".g", "z", ".D", ".Dh", "f", "Y", ".Rh", ".L", "n2",]

[alternates]
A = [ "aa",]
I = [ "ii", "ee",]
U = [ "uu",]
R = [ "RRi", "R^i",]
RR = [ "RRI", "R^I",]
LLi = [ "L^i",]
LLI = [ "L^I",]
M = [ ".m", ".n",]
ch = [ "c",]
Ch = [ "C",]
jh = [ "J",]
ph = [ "P",]
bh = [ "B",]
"~n" = [ "JN",]
v = [ "w",]
Sh = [ "S",]
x = [ "kS", "ksh",]
jn = [ "GY", "dny",]
"|" = [ ".",]
"||" = [ "..",]
z = [ "J",]
