[vowels]
"рдЕ" = "ЁРОа"
"рдЖ" = "ЁРОа"
"рдЗ" = "ЁРОб"
"рдИ" = "ЁРОб"
"рдЙ" = "ЁРОв"
"рдК" = "ЁРОв"
"рдЛ" = "ЁРО╜ЁРОв"
"реа" = "ЁРО╜ЁРОв"
"рдМ" = "ЁРО╛ЁРОв"
"реб" = "ЁРО╛ЁРОв"
"рдО" = ""
"рдП" = "ЁРОб"
"рдР" = "ЁРОаЁРОб"
"рдТ" = ""
"рдУ" = "ЁРОв"
"рдФ" = "ЁРОаЁРОв"

[virama]
"реН" = ""

[consonants]
"рдХ" = "ЁРОг"
"рдЦ" = "ЁРОз"
"рдЧ" = "ЁРОе"
"рдШ" = "ЁРОе"
"рдЩ" = "ЁРО┤"
"рдЪ" = "ЁРОи"
"рдЫ" = "ЁРОи"
"рдЬ" = "ЁРОй"
"рдЭ" = "ЁРОй"
"рдЮ" = "ЁРО┤"
"рдЯ" = "ЁРОл"
"рда" = "ЁРОл"
"рдб" = "ЁРОн"
"рдв" = "ЁРОн"
"рдг" = "ЁРО┤"
"рдд" = "ЁРОл"
"рде" = "ЁРО░"
"рдж" = "ЁРОн"
"рдз" = "ЁРОн"
"рди" = "ЁРО┤"
"рдк" = "ЁРО▒"
"рдл" = "ЁРО▒"
"рдм" = "ЁРО▓"
"рдн" = "ЁРО▓"
"рдо" = "ЁРО╢"
"рдп" = "ЁРО╣"
"рд░" = "ЁРО╝"
"рд▓" = "ЁРО╛"
"рд╡" = "ЁРО║"
"рд╢" = "ЁРПБ"
"рд╖" = "ЁРПВ"
"рд╕" = "ЁРО┐"
"рд╣" = "ЁРПГ"
"рд│" = "ЁРО╛"
"рдХреНрд╖" = "ЁРОгЁРПВ"
"рдЬреНрдЮ" = "ЁРОйЁРО┤"

[symbols]
"реж" = ""
"рез" = "ЁРПС"
"реи" = "ЁРПТ"
"рей" = "ЁРПТЁРПС"
"рек" = "ЁРПТЁРПТ"
"рел" = "ЁРПТЁРПТЁРПС"
"рем" = "ЁРПТЁРПТЁРПТ"
"рен" = "ЁРПТЁРПТЁРПТЁРПС"
"рео" = "ЁРПТЁРПТЁРПТЁРПТ"
"реп" = "ЁРПТЁРПТЁРПТЁРПТЁРПС"
"реР" = "ЁРОвЁРО╢"
"рд╜" = ""
"ред" = "ред"
"рее" = "рее"

[candra]
"реЕ" = "ЁРОб"
