[vowels]
"अ" = "a"
"आ" = "A"
"इ" = "i"
"ई" = "I"
"उ" = "u"
"ऊ" = "U"
"ऋ" = "f"
"ॠ" = "F"
"ऌ" = "x"
"ॡ" = "X"
"ऎ" = "è"
"ए" = "e"
"ऐ" = "E"
"ऒ" = "ò"
"ओ" = "o"
"औ" = "O"

[yogavaahas]
"ं" = "M"
"ः" = "H"
"ँ" = "~"

[virama]
"्" = ""

[consonants]
"क" = "k"
"ख" = "K"
"ग" = "g"
"घ" = "G"
"ङ" = "N"
"च" = "c"
"छ" = "C"
"ज" = "j"
"झ" = "J"
"ञ" = "Y"
"ट" = "w"
"ठ" = "W"
"ड" = "q"
"ढ" = "Q"
"ण" = "R"
"त" = "t"
"थ" = "T"
"द" = "d"
"ध" = "D"
"न" = "n"
"प" = "p"
"फ" = "P"
"ब" = "b"
"भ" = "B"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = "S"
"ष" = "z"
"स" = "s"
"ह" = "h"
"ळ" = "L"
"क्ष" = "kz"
"ज्ञ" = "jY"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "oM"
"ऽ" = "'"
"।" = "."
"॥" = ".."

[accents]
"॑" = "̭"
"॒" = "॒"
"᳡" = "̀"
"꣡" = "/"
"꣢" = "²"
"꣣" = "³"
"꣤" = "⁴"
"꣥" = "⁵"
"꣦" = "⁶"
"꣧" = "⁷"
"꣨" = "⁸"
"꣩" = "⁹"
"꣪" = "꣪"
"꣫" = "꣫"
"꣬" = "꣬"
"꣭" = "꣭"
"꣮" = "꣮"
"꣯" = "꣯"
"꣰" = "꣰"
"꣱" = "꣱"

[extra_consonants]
"क़" = "k0"
"ख़" = "K0"
"ग़" = "g0"
"ज़" = "j0"
"ड़" = "q0"
"ढ़" = "Q0"
"फ़" = "P0"
"य़" = "Y0"
"ऱ" = "r2"
"ऴ" = "L0"
