vowels = [ "a", "ā", "i", "ī", "u", "ū", "r̥", "r̥̄", "l̥", "l̥̄", "ĕ", "e", "ai", "ŏ", "o", "au", "æ", "ô",]
yogavaahas = [ "ṃ", "ḥ", "m̐",]
virama = [ "",]
consonants = [ "k", "kʰ", "g", "gʰ", "ṅ", "c", "cʰ", "j", "jʰ", "ñ", "ṭ", "ṭʰ", "ḍ", "ḍʰ", "ṇ", "t", "tʰ", "d", "dʰ", "n", "p", "pʰ", "b", "bʰ", "m", "y", "r", "l", "v", "ś", "ṣ", "s", "h", "ḷ", "kṣ", "jñ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "oṃ", "'", ".", "..",]
zwj = [ "\u200d",]
skip = [ "",]
candra = [ "æ",]
extra_consonants = [ "q", "k͟ʰ", "ġ", "z", "ṛ", "ṛʰ", "f", "ẏ", "ṟ", "ḻ",]

[alternates]
"m̐" = [ "ṁ",]
"oṃ" = [ "ŏṃ",]
"r̥̄" = [ "r̥̄",]
"." = [ "|", "/",]
".." = [ "||", "//",]
