vowels = [ "a", "aa", "i", "ii", "u", "uu", ".r", ".rr", ".l", ".ll", "è", "e", "ai", "ò", "o", "au",]
yogavaahas = [ ".m", ".h", "~m",]
virama = [ "",]
consonants = [ "k", "kh", "g", "gh", "\"n", "c", "ch", "j", "jh", "~n", ".t", ".th", ".d", ".dh", ".n", "t", "th", "d", "dh", "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "\"s", ".s", "s", "h", "L", "k.s", "j~n",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "O", ".a", "|", "||",]
