[vowels]
"अ" = "a"
"आ" = "A"
"इ" = "i"
"ई" = "I"
"उ" = "u"
"ऊ" = "U"
"ऋ" = "q"
"ॠ" = "Q"
"ऌ" = "L"
"ॡ" = "ḹ"
"ऎ" = "è"
"ए" = "e"
"ऐ" = "E"
"ऒ" = ""
"ओ" = "o"
"औ" = "O"

[yogavaahas]
"ं" = "M"
"ः" = "H"
"ँ" = "z"

[virama]
"्" = ""

[consonants]
"क" = "k"
"ख" = "K"
"ग" = "g"
"घ" = "G"
"ङ" = "f"
"च" = "c"
"छ" = "C"
"ज" = "j"
"झ" = "J"
"ञ" = "F"
"ट" = "t"
"ठ" = "T"
"ड" = "d"
"ढ" = "D"
"ण" = "N"
"त" = "w"
"थ" = "W"
"द" = "x"
"ध" = "X"
"न" = "n"
"प" = "p"
"फ" = "P"
"ब" = "b"
"भ" = "B"
"म" = "m"
"य" = "y"
"र" = "r"
"ल" = "l"
"व" = "v"
"श" = "S"
"ष" = "R"
"स" = "s"
"ह" = "h"
"ळ" = "l̤"
"क्ष" = "kR"
"ज्ञ" = "jF"

[symbols]
"०" = "0"
"१" = "1"
"२" = "2"
"३" = "3"
"४" = "4"
"५" = "5"
"६" = "6"
"७" = "7"
"८" = "8"
"९" = "9"
"ॐ" = "oM"
"ऽ" = "'"
"।" = "."
"॥" = ".."
